
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('medications').del()
    .then(function () {
      // Inserts seed entries
      return knex('medications').insert([
        {
          "id": 40812,
          "name": "CLORIDRATO DE NORTRIPTILINA",
          "pharmaco": null,
          "pharmacos": "NORTRIPTILINA",
          "concentration": "50",
          "unit": "MG",
          "type_medication": "GENERICO",
          "pharmaceutical_form": "CAPSULA",
          "via_administration": "ORAL",
          "code_atc": "N06AA10",
          "use_intern": true,
          "antimicrobial": false,
          "bula": null,
          "ordinance": "LISTA - C1",
          "control_special": false,
          "tiss": "??",
          "mip": false,
          "label": "CLORIDRATO DE NORTRIPTILINA 50MG - CAPSULA",
          "Unified": null
        },
        {
          "id": 40813,
          "name": "CLORIDRATO DE NORTRIPTILINA",
          "pharmaco": null,
          "pharmacos": "NORTRIPTILINA",
          "concentration": "50",
          "unit": "MG",
          "type_medication": "GENERICO",
          "pharmaceutical_form": "CAPSULA",
          "via_administration": "ORAL",
          "code_atc": "N06AA10",
          "use_intern": true,
          "antimicrobial": false,
          "bula": null,
          "ordinance": "LISTA - C1",
          "control_special": false,
          "tiss": "??",
          "mip": false,
          "label": "CLORIDRATO DE NORTRIPTILINA 50MG - CAPSULA",
          "Unified": null
        },
        {
          "id": 40814,
          "name": "CLORIDRATO DE NORTRIPTILINA",
          "pharmaco": null,
          "pharmacos": "NORTRIPTILINA",
          "concentration": "50",
          "unit": "MG",
          "type_medication": "GENERICO",
          "pharmaceutical_form": "CAPSULA",
          "via_administration": "ORAL",
          "code_atc": "N06AA10",
          "use_intern": true,
          "antimicrobial": false,
          "bula": null,
          "ordinance": "LISTA - C1",
          "control_special": false,
          "tiss": "??",
          "mip": false,
          "label": "CLORIDRATO DE NORTRIPTILINA 50MG - CAPSULA",
          "Unified": null
        },
        {
          "id": 40815,
          "name": "CLORIDRATO DE NORTRIPTILINA",
          "pharmaco": null,
          "pharmacos": "NORTRIPTILINA",
          "concentration": "50",
          "unit": "MG",
          "type_medication": "GENERICO",
          "pharmaceutical_form": "CAPSULA",
          "via_administration": "ORAL",
          "code_atc": "N06AA10",
          "use_intern": true,
          "antimicrobial": false,
          "bula": null,
          "ordinance": "LISTA - C1",
          "control_special": false,
          "tiss": "??",
          "mip": false,
          "label": "CLORIDRATO DE NORTRIPTILINA 50MG - CAPSULA",
          "Unified": null
        },
        {
          "id": 10044,
          "name": "DEPOFLOX",
          "pharmaco": null,
          "pharmacos": "FLUOXETINA",
          "concentration": "20",
          "unit": "MG",
          "type_medication": "SIMILAR",
          "pharmaceutical_form": "CAPSULA",
          "via_administration": "ORAL",
          "code_atc": "N06AB03",
          "use_intern": true,
          "antimicrobial": false,
          "bula": null,
          "ordinance": "LISTA - C1",
          "control_special": false,
          "tiss": "510808001115412",
          "mip": false,
          "label": "DEPOFLOX 20MG - CAPSULA",
          "Unified": null
        },
        {
          "id": 10057,
          "name": "DEPRAX",
          "pharmaco": null,
          "pharmacos": "FLUOXETINA",
          "concentration": "20",
          "unit": "MG",
          "type_medication": "SIMILAR",
          "pharmaceutical_form": "CAPSULA",
          "via_administration": "ORAL",
          "code_atc": "N06AB03",
          "use_intern": true,
          "antimicrobial": false,
          "bula": null,
          "ordinance": "LISTA - C1",
          "control_special": false,
          "tiss": "500502501113416",
          "mip": false,
          "label": "DEPRAX 20MG - CAPSULA",
          "Unified": null
        },
        {
          "id": 28438,
          "name": "ZOLAMOX",
          "pharmaco": null,
          "pharmacos": "ACETAZOLAMIDA",
          "concentration": "250",
          "unit": "MG",
          "type_medication": "SIMILAR",
          "pharmaceutical_form": "COMPRIMIDO",
          "via_administration": "ORAL",
          "code_atc": "S01EC01",
          "use_intern": true,
          "antimicrobial": false,
          "bula": null,
          "ordinance": "",
          "control_special": false,
          "tiss": "0000012440",
          "mip": false,
          "label": "ZOLAMOX 250MG - COMPRIMIDO",
          "Unified": null
        },
        {
          "id": 39930,
          "name": "LIDOCAINA + OXITETRACICLINA",
          "pharmaco": null,
          "pharmacos": "LIDOCAINA,OXITETRACICLINA",
          "concentration": "20 + 50",
          "unit": "MG/ML",
          "type_medication": "GENERICO",
          "pharmaceutical_form": "SOLUCAO INJETAVEL",
          "via_administration": "SUBCUTÂNEA",
          "code_atc": "J01AA56",
          "use_intern": true,
          "antimicrobial": true,
          "bula": "http://www.anvisa.gov.br/datavisa/fila_bula/frmVisualizarbula.asp?pNuTransacao=23081212017&pIdAnexo=10304631",
          "ordinance": "",
          "control_special": false,
          "tiss": "0000002145",
          "mip": false,
          "label": "LIDOCAINA + OXITETRACICLINA 20 + 50MG/ML - SOLUCAO INJETAVEL",
          "Unified": null
        },
        {
          "id": 26028,
          "name": "TERRA - CORTRIL",
          "pharmaco": null,
          "pharmacos": "HIDROCORTISONA,OXITETRACICLINA",
          "concentration": "10 + 30",
          "unit": "MG/G",
          "type_medication": "REFERENCIA",
          "pharmaceutical_form": "POMADA DERMATOLOGICA",
          "via_administration": "TOP",
          "code_atc": "D07XA01",
          "use_intern": true,
          "antimicrobial": true,
          "bula": null,
          "ordinance": "",
          "control_special": false,
          "tiss": "0000002144",
          "mip": false,
          "label": "TERRA - CORTRIL 10 + 30MG/G - POMADA DERMATOLOGICA",
          "Unified": null
        }
      ]);
    });
};
