export const drugs: { nome: string }[] = [
  { nome: 'ACIDO CITRICO' },
  { nome: 'CARBONATO DE SODIO' },
  { nome: 'BICARBONATO DE SODIO' },
  { nome: 'EMULSAO DE SIMETICONE 30%' },
  { nome: 'DIMETICONA' },
  { nome: 'HIDROXIDO DE MAGNESIO' },
  { nome: 'MAGNESIO' },
  { nome: 'SIMETICONA' },
  { nome: 'CAOLIM COLOIDAL' },
  { nome: 'PECTINA CITRICA' },
  { nome: 'HIDROXIDO DE ALUMINIO' },
  { nome: 'FLUORETO DE SODIO' },
  { nome: 'CARBONATO DE CALCIO' },
  { nome: 'CLORIDRATO DE RANITIDINA' },
  { nome: 'OMEPRAZOL MICROGRANULADOS' },
  { nome: 'RABEPRAZOL SODICO' },
  { nome: 'ESOMEPRAZOL MAGNESICO' },
  { nome: 'PANTOPRAZOL SODICO SESQUI-HIDRATADO' },
  { nome: 'PANTOPRAZOL' },
  { nome: 'DEXLANSOPRAZOL' },
  { nome: 'LANSOPRAZOL' },
  { nome: 'CLARITROMICINA' },
  { nome: 'AMOXICILINA TRI-HIDRATADA' },
  { nome: 'PANTOPRAZOL MAGNESICO DI-HIDRATADO' },
  { nome: 'PANTOPRAZOL SODICO SESQUI-HIIDRATADO' },
  { nome: 'OMEPRAZOL SODICO' },
  { nome: 'PANTOPRAZOL SODICO' },
  { nome: 'ESOMEPRAZOL' },
  { nome: 'CARBONATO DE MAGNESIO' },
  { nome: 'CARBONATO BASICO DE BISMUTO' },
  { nome: 'SALICILATO DE BISMUTO MONOBASICO' },
  { nome: 'CIMETIDINA' },
  { nome: 'RANITIDINA' },
  { nome: 'FAMOTIDINA' },
  { nome: 'NIZATIDINA' },
  { nome: 'OMEPRAZOL' },
  { nome: 'BROMOPRIDA' },
  { nome: 'ALGINATO DE SODIO' },
  { nome: 'SULFATO DE ATROPINA' },
  { nome: 'BUTILBROMETO DE ESCOPOLAMINA' },
  { nome: 'BROMETO DE PINAVERIO' },
  { nome: 'CLORIDRATO DE MEBEVERINA' },
  { nome: 'BROMETO DE OTILONIO' },
  { nome: 'DICICLOVERINA' },
  { nome: 'PRUCALOPRIDA' },
  { nome: 'FOSFATIDILSERINA' },
  { nome: 'PANCREATINA' },
  { nome: 'HOMATROPINA' },
  { nome: 'DIASTASE' },
  { nome: 'NICOTINAMIDA' },
  { nome: 'PEPSINA' },
  { nome: 'PINAVERIO' },
  { nome: 'BELADONA' },
  { nome: 'CLORETO DE CALCIO' },
  { nome: 'RUIBARBO' },
  { nome: 'ATROPINA' },
  { nome: 'ESCOPOLAMINA' },
  { nome: 'DIPIRONA MONOIDRATADA' },
  { nome: 'DIPIRONA' },
  { nome: 'BROMETO DE N-BUTILESCOPOLAMINA' },
  { nome: 'PARACETAMOL' },
  { nome: 'MALEATO DE TRIMEBUTINA' },
  { nome: 'CLORIDRATO DE METOCLOPRAMIDA' },
  { nome: 'CLORIDRATO DE METOCLOPRAMIDA MONOIDRATADO' },
  { nome: 'DIMENIDRINATO' },
  { nome: 'DOMPERIDONA' },
  { nome: 'PIRIDOXINA' },
  { nome: 'CELULASE' },
  { nome: 'METOCLOPRAMIDA' },
  { nome: 'BROMELAINA' },
  { nome: 'DEIDROCOLATO DE SODIO' },
  { nome: 'CLORIDRATO DE ONDANSETRONA' },
  { nome: 'CLORIDRATO DE ONDANSETRONA DI-HIDRATADO' },
  { nome: 'FOSAPREPITANTO DIMEGLUMINA' },
  { nome: 'MECLOZINA' },
  { nome: 'CLORIDRATO DE PIRIDOXINA' },
  { nome: 'ONDANSETRONA' },
  { nome: 'GRANISETRONA' },
  { nome: 'DOLASETRON' },
  { nome: 'PALONOSETRONA' },
  { nome: 'APREPITANTO' },
  { nome: 'RACEMETIONINA' },
  { nome: 'METIONINA (11 C)' },
  { nome: 'CITRATO DE COLINA' },
  { nome: 'BETAINA' },
  { nome: 'DL-METIONINA' },
  { nome: 'SILIMARINA' },
  { nome: 'ARGININA' },
  { nome: 'TAURINA' },
  { nome: 'ORNITINA' },
  { nome: 'PICOSSULFATO DE SODIO' },
  { nome: 'PICOSSULFATO DE SODIO MONOIDRATADO' },
  { nome: 'FOSFATO DE SODIO MONOBASICO MONOIDRATADO' },
  { nome: 'FOSFATO DE SODIO DIBASICO HEPTAIDRATADO' },
  { nome: 'FOSFATO DE SODIO MONOBASICO' },
  { nome: 'FOSFATO DE SODIO DIBASICO' },
  { nome: 'FOSFATO DE SODIO MONOBASICO MONOHIDRATADO' },
  { nome: 'FOSFATO DE SODIO DIBASICO HEPTAHIDRATADO' },
  { nome: 'OLEO MINERAL' },
  { nome: 'AGAR' },
  { nome: 'FENOLFTALEINA' },
  { nome: 'BISACODIL' },
  { nome: 'DOCUSATO SODICO' },
  { nome: 'PLANTAGO OVATA' },
  { nome: 'SACARINA SODICA' },
  { nome: 'PARAFINA' },
  { nome: 'PSYLLIUM PLANTAGO' },
  { nome: 'LACTULOSE' },
  { nome: 'LACTITOL' },
  { nome: 'MACROGOL' },
  { nome: 'MANITOL' },
  { nome: 'FOSFATO DE POTASSIO MONOBASICO' },
  { nome: 'FOSFATO DE POTASSIO' },
  { nome: 'GLICEROL' },
  { nome: 'METILNALTREXONA' },
  { nome: 'GLICERINA' },
  { nome: 'NISTATINA' },
  { nome: 'NIFUROXAZIDA' },
  { nome: 'CARVAO VEGETAL ATIVADO' },
  { nome: 'SALICILATO DE BISMUTO' },
  { nome: 'CITRATO DE SODIO' },
  { nome: 'CLORETO DE POTASSIO' },
  { nome: 'CLORETO DE SODIO' },
  { nome: 'GLICOSE' },
  { nome: 'DIFENOXILATO' },
  { nome: 'LOPERAMIDA' },
  { nome: 'BUDESONIDA' },
  { nome: 'SULFASSALAZINA' },
  { nome: 'MESALAZINA' },
  { nome: 'PRODUTOS SEM SUBSTANCIA ESPECIFICA' },
  { nome: 'SACCHAROMYCES BOULARDII - 17' },
  { nome: 'SACCHAROMYCES CEREVISAE' },
  { nome: 'SACCHAROMYCES BOULARDII' },
  { nome: 'RACECADOTRIL' },
  { nome: 'CLORIDRATO DE SIBUTRAMINA MONOIDRATADO' },
  { nome: 'CLORIDRATO DE SIBUTRAMINA' },
  { nome: 'CLORIDRATO DE LORCASSERINA HEMI-HIDRATADO' },
  { nome: 'FEMPROPOREX' },
  { nome: 'ANFEPRAMONA' },
  { nome: 'MAZINDOL' },
  { nome: 'SIBUTRAMINA' },
  { nome: 'ORLISTATE' },
  { nome: 'ENZIMAS PANCREATICAS' },
  { nome: 'INSULINA LISPRO' },
  { nome: 'INSULINA ASPARTE' },
  { nome: 'INSULINA GLULISINA' },
  { nome: 'INSULINA HUMANA' },
  { nome: 'INSULINA BIFASICA' },
  { nome: 'INSULINA GLARGINA' },
  { nome: 'INSULINA NEUTRA' },
  { nome: 'GLIMEPIRIDA' },
  { nome: 'METFORMINA' },
  { nome: 'GLIBENCLAMIDA' },
  { nome: 'CLORPROPAMIDA' },
  { nome: 'GLIPIZIDA' },
  { nome: 'GLICLAZIDA' },
  { nome: 'PIOGLITAZONA' },
  { nome: 'SITAGLIPTINA' },
  { nome: 'ALOGLIPTINA' },
  { nome: 'SAXAGLIPTINA' },
  { nome: 'LINAGLIPTINA' },
  { nome: 'REPAGLINIDA' },
  { nome: 'EXENATIDA' },
  { nome: 'DAPAGLIFLOZINA' },
  { nome: 'LIXISENATIDA' },
  { nome: 'CLORIDRATO DE METFORMINA' },
  { nome: 'FOSFATO DE SITAGLIPTINA' },
  { nome: 'ACIDO ASCORBICO' },
  { nome: 'SULFATO FERROSO' },
  { nome: 'SULFATO DE POTASSIO' },
  { nome: 'SULFATO DE MANGANES' },
  { nome: 'SULFATO DE MAGNESIO' },
  { nome: 'RUTOSIDEO' },
  { nome: 'RIBOFLAVINA' },
  { nome: 'PANTENOL' },
  { nome: 'PALMITATO DE RETINOL' },
  { nome: 'NITRATO DE TIAMINA' },
  { nome: 'IODETO DE POTASSIO' },
  { nome: 'FOSFATO DE CALCIO DIBASICO' },
  { nome: 'COLECALCIFEROL' },
  { nome: 'BETACAROTENO' },
  { nome: 'ZINCO' },
  { nome: 'SELENIO' },
  { nome: 'COBRE' },
  { nome: 'ALFA-TOCOFEROL' },
  { nome: 'TRIPTOFANA' },
  { nome: 'TREONINA' },
  { nome: 'SULFATO DE ZINCO' },
  { nome: 'RETINOL' },
  { nome: 'PANTOTENATO DE CALCIO' },
  { nome: 'LISINA' },
  { nome: 'CLORIDRATO DE TIAMINA' },
  { nome: 'CIANOCOBALAMINA' },
  { nome: 'COLECALFICEROL' },
  { nome: 'CALCIFEROL' },
  { nome: 'CALCIO' },
  { nome: 'POLIMINERAIS' },
  { nome: 'POLIVITAMINICOS' },
  { nome: 'CIPROEPTADINA' },
  { nome: 'PROPILENOGLICOL' },
  { nome: 'TIAMINA' },
  { nome: 'ACIDO FOSFORICO' },
  { nome: 'PIRODOXINA' },
  { nome: 'ACIDO FOLICO' },
  { nome: 'VITAMINAS' },
  { nome: 'OLEO DE FIGADO DE BACALHAU' },
  { nome: 'POLIVITAMINAS' },
  { nome: 'TRIPTOFANO' },
  { nome: 'FRUTOSE' },
  { nome: 'FOSFATO SODICO DE RIBOFLAVINA' },
  { nome: 'DEXPANTENOL' },
  { nome: 'ACETATO DE RACEALFATOCOFEROL' },
  { nome: 'ACETATO DE RETINOL' },
  { nome: 'TOCOFEROL' },
  { nome: 'ALFACALCIDOL' },
  { nome: 'MONONITRATO DE TIAMINA' },
  { nome: 'SULBUTIAMINA' },
  { nome: 'FOSFATO DE RIBOFLAVINA' },
  { nome: 'FLUOR' },
  { nome: 'COMPLEXO B' },
  { nome: 'FUMARATO FERROSO' },
  { nome: 'POLIVITAMICOS' },
  { nome: 'HESPERIDINA' },
  { nome: 'PIPERIDOLATO' },
  { nome: 'POTASSIO' },
  { nome: 'LACTOGLICONATO DE CALCIO' },
  { nome: 'ASPARTATO DE MAGNESIO' },
  { nome: 'ASPARTATO DE POTASSIO' },
  { nome: 'LISADO DE ORGAOS' },
  { nome: 'BIOTINA' },
  { nome: 'ACIDOS GRAXOS' },
  { nome: 'OMEGA 3' },
  { nome: 'GLICONATO DE CALCIO' },
  { nome: 'CITRATO POTASSIO' },
  { nome: 'SULFATO DE ZINCO HEPTAIDRATADO' },
  { nome: 'COMPLEXO OSSEINA HIDROXIAPATITA' },
  { nome: 'OXIDO CUPRICO' },
  { nome: 'SULFATO DE ZINCO MONOIDRATADO' },
  { nome: 'CLORIDRATO DE ARGININA' },
  { nome: 'CITRULINA' },
  { nome: 'ASPARTATO DE ORNITINA' },
  { nome: 'ACIDO GAMAMINOBUTIRICO' },
  { nome: 'CLORIDRATO DE LISINA' },
  { nome: 'CLORIDRATO DE CIPROEPTADINA' },
  { nome: 'COBAMAMIDA' },
  { nome: 'ASPARTATO DE ARGININA' },
  { nome: 'ASPARTATO DE L-ARGININA' },
  { nome: 'GALSULFASE' },
  { nome: 'ACETILCISTEINA' },
  { nome: 'POLIAMINOACIDOS' },
  { nome: 'CARNITINA' },
  { nome: 'ADENOSINA' },
  { nome: 'BETACINA' },
  { nome: 'COLINA' },
  { nome: 'METIONINA' },
  { nome: 'SORBITOL' },
  { nome: 'LEVOCARNITINA' },
  { nome: 'ALFATALIGLICERASE' },
  { nome: 'ALFAELOSULFASE' },
  { nome: 'VARFARINA' },
  { nome: 'HEPARINA' },
  { nome: 'ANTITROMBINA III' },
  { nome: 'ENOXAPARINA' },
  { nome: 'NADROPARINA CALCICA' },
  { nome: 'CLOPIDOGREL' },
  { nome: 'TICLOPIDINA' },
  { nome: 'ACIDO ACETILSALICILICO' },
  { nome: 'TRIFLUSAL' },
  { nome: 'TREPROSTINILA' },
  { nome: 'ESTREPTOQUINASE' },
  { nome: 'ALTEPLASE' },
  { nome: 'ALFADOTRECOGINA' },
  { nome: 'TENECTEPLASE' },
  { nome: 'APIXABANA' },
  { nome: 'BEMIPARINA SODICA' },
  { nome: 'DALTEPARINA SODICA' },
  { nome: 'ENOXAPARINA SODICA' },
  { nome: 'GLICINATO DE ALUMINIO' },
  { nome: 'BISSULFATO DE CLOPIDOGREL' },
  { nome: 'ABCIXIMABE' },
  { nome: 'ACIDO EPSILON AMINOCAPROICO' },
  { nome: 'ANTIGENOS MISTOS' },
  { nome: 'ACIDO TRANEXAMICO' },
  { nome: 'APROTININA' },
  { nome: 'FIBRINOGENIO' },
  { nome: 'TROMBINA' },
  { nome: 'IDARUCIZUMABE' },
  { nome: 'FITOMENADIONA' },
  { nome: 'FIBRINA' },
  { nome: 'GELATINA' },
  { nome: 'COMPLEXO PROTROMBINICO PARCIALMENTE ATIVADO' },
  { nome: 'ALFAMOROCTOCOGUE' },
  { nome: 'FATOR DE COAGULACAO IX' },
  { nome: 'FATOR DE COAGULACAO VIII' },
  { nome: 'FATOR DE COAGULACAO VIII E IX' },
  { nome: 'FATOR DE COAGULACAO XIII' },
  { nome: 'ALFAEPTACOGUE ATIVADO' },
  { nome: 'CARBAZOCROMO' },
  { nome: 'FATOR VIII DE COAGULACAO' },
  { nome: 'FATOR DE VON WILLEBRAND' },
  { nome: 'ALFASIMOCTOCOGUE' },
  { nome: 'ALFAOCTOCOGUE' },
  { nome: 'FATOR VON WILLEBRAND' },
  { nome: 'FATOR IX DE COAGULACAO' },
  { nome: 'FATOR X DE COAGULACAO' },
  { nome: 'FATOR VII DE COAGULACAO' },
  { nome: 'FATOR II DE COAGULACAO' },
  { nome: 'FATOR X' },
  { nome: 'PROTEINA PLASMATICA HUMANA COM UMA ATIVIDADE DE FEIBA' },
  { nome: 'FATOR XIII DE COAGULACAO' },
  { nome: 'ELTROMBOPAGUE OLAMINA' },
  { nome: 'FERRIPOLIMALTOSE' },
  { nome: 'SACARATO DE HIDROXIDO FERRICO' },
  { nome: 'SULFATO FERROSO HEPTAIDRATADO' },
  { nome: 'FERRO' },
  { nome: 'FERROCARBONILA' },
  { nome: 'ASSOC' },
  { nome: 'GLUCONATO FERROSO' },
  { nome: 'CITRATO FERRICO AMONIACAL' },
  { nome: 'CARBOXIMALTOSE FERRICA' },
  { nome: 'HIDROXIDO DE FERRO III' },
  { nome: 'BISGLICINATO FERROSO' },
  { nome: 'COBALAMINA' },
  { nome: 'FERRO QUELATO' },
  { nome: 'MECOBALAMINA' },
  { nome: 'INOSITOL' },
  { nome: 'DEXAMETASONA' },
  { nome: 'EXTRATO DE FIGADO' },
  { nome: 'MANGANES' },
  { nome: 'PROCAINA' },
  { nome: 'ERITROPOETINA HUMANA RECOMBINANTE' },
  { nome: 'ALFADARBEPOETINA' },
  { nome: 'ACETATO DE DEXTROALFATOCOFEROL' },
  { nome: 'TETAEPOETINA' },
  { nome: 'EPOETINA BETA' },
  { nome: 'ERITROPOIETINA' },
  { nome: 'ALFAEPOETINA' },
  { nome: 'EPOETINA ALFA' },
  { nome: 'ALBUMINA HUMANA' },
  { nome: 'HIDROXIETILAMIDO' },
  { nome: 'HETAMIDO' },
  { nome: 'AMINOACIDOS' },
  { nome: 'POLIMINERIAIS' },
  { nome: 'CLORETO DE CALCIO DIIDRATADO' },
  { nome: 'LACTATO DE SODIO' },
  { nome: 'RINGER LACTATO' },
  { nome: 'SOLUCAO INTRAVENOSA ELETROLITICA' },
  { nome: 'CLORETO DE CALCIO DI-HIDRATADO' },
  { nome: 'GLICINA' },
  { nome: 'ACETATO SODIO' },
  { nome: 'HIALURONIDASE' },
  { nome: 'INIBIDOR DE C1 ESTERASE DERIVADO DE PLASMA HUMANO' },
  { nome: 'DIGOXINA' },
  { nome: 'CLORIDRATO DE PROPAFENONA' },
  { nome: 'QUINIDINA' },
  { nome: 'DISOPIRAMIDA' },
  { nome: 'PROPAFENONA' },
  { nome: 'AMIODARONA' },
  { nome: 'DRONEDARONA' },
  { nome: 'VERNACALANTO' },
  { nome: 'HEMITARTARATO DE METARAMINOL' },
  { nome: 'CLORIDRATO DE DOBUTAMINA' },
  { nome: 'NOREPINEFRINA' },
  { nome: 'DOPAMINA' },
  { nome: 'DOBUTAMINA' },
  { nome: 'EPINEFRINA' },
  { nome: 'RANOLAZINA' },
  { nome: 'NITROGLICERINA' },
  { nome: 'PROPATILNITRATO' },
  { nome: 'DINITRATO DE ISOSSORBIDA' },
  { nome: 'MONONITRATO DE ISOSSORBIDA' },
  { nome: 'TRAPIDIL' },
  { nome: 'NESIRITIDA' },
  { nome: 'UBIDECARENONA' },
  { nome: 'TRIMETAZIDINA' },
  { nome: 'MESILATO DE DOXAZOSINA' },
  { nome: 'CLORIDRATO DE HIDRALAZINA' },
  { nome: 'METILDOPA' },
  { nome: 'MOXONIDINA' },
  { nome: 'PRAZOSINA' },
  { nome: 'DOXAZOSINA' },
  { nome: 'NITROPRUSSETO DE SODIO' },
  { nome: 'BOSENTANA' },
  { nome: 'CLORTALIDONA' },
  { nome: 'RESERPINA' },
  { nome: 'FUROSEMIDA' },
  { nome: 'HIDROCLOROTIAZIDA' },
  { nome: 'OLMESARTANA' },
  { nome: 'IRBESARTANA' },
  { nome: 'LOSARTAN' },
  { nome: 'LOSARTANA' },
  { nome: 'METOPROLOL' },
  { nome: 'LISINOPRIL' },
  { nome: 'VALSARTAN' },
  { nome: 'RAMIPRIL' },
  { nome: 'PROPRANOLOL' },
  { nome: 'TRIANTERENO' },
  { nome: 'INDAPAMIDA' },
  { nome: 'PIRETANIDA' },
  { nome: 'ESPIRONOLACTONA' },
  { nome: 'AMILORIDA' },
  { nome: 'DICLORIDRATO DE FLUNARIZINA' },
  { nome: 'FENTOLAMINA' },
  { nome: 'PENTOXIFILINA' },
  { nome: 'CODERGOCRINA' },
  { nome: 'DIIDROERGOCRISTINA' },
  { nome: 'LOMIFILINA' },
  { nome: 'BENCICLANO' },
  { nome: 'POLICRESULENO' },
  { nome: 'CLORIDRATO DE CINCHOCAINA' },
  { nome: 'LIDOCAINA' },
  { nome: 'PRILOCAINA' },
  { nome: 'TRIBENOSIDO' },
  { nome: 'CINCHOCAINA' },
  { nome: 'POLISSULFATO DE MUCOPOLISSACARIDEO' },
  { nome: 'MUCOPOLISSACARIDEO' },
  { nome: 'ASSOCIACAO' },
  { nome: 'NICOTINATO DE BENZILA' },
  { nome: 'CLORETO DE MAGNESIO' },
  { nome: 'DIOSMINA' },
  { nome: 'DOBESILATO DE CALCIO' },
  { nome: 'HIDROSMINA' },
  { nome: 'MACITENTANA' },
  { nome: 'ILOPROSTA' },
  { nome: 'TARTARATO DE METOPROLOL' },
  { nome: 'HEMIFUMARATO DE BISOPROLOL' },
  { nome: 'SUCCINATO DE METOPROLOL' },
  { nome: 'CLORIDRATO DE SOTALOL' },
  { nome: 'CLORIDRATO DE ESMOLOL' },
  { nome: 'NADOLOL' },
  { nome: 'ATENOLOL' },
  { nome: 'BISOPROLOL' },
  { nome: 'NEBIVOLOL' },
  { nome: 'CARVEDILOL' },
  { nome: 'NIFEDIPINO' },
  { nome: 'CLORIDRATO DE LERCANIDIPINO' },
  { nome: 'CLORIDRATO DE VERAPAMIL' },
  { nome: 'BESILATO DE LEVANLODIPINO' },
  { nome: 'CLORIDRATO DE DILTIAZEM' },
  { nome: 'ANLODIPINO' },
  { nome: 'FELODIPINO' },
  { nome: 'ISRADIPINO' },
  { nome: 'NIMODIPINO' },
  { nome: 'NITRENDIPINO' },
  { nome: 'VERAPAMIL' },
  { nome: 'DILTIAZEM' },
  { nome: 'MALEATO DE ENALAPRIL' },
  { nome: 'PERINDOPRIL' },
  { nome: 'CAPTOPRIL' },
  { nome: 'ENALAPRIL' },
  { nome: 'PERINDOPRIL ERBUMINA' },
  { nome: 'QUINAPRIL' },
  { nome: 'FOSINOPRIL' },
  { nome: 'TRANDOLAPRIL' },
  { nome: 'DELAPARILA' },
  { nome: 'PERINDOPRIL ARGININA' },
  { nome: 'BESILATO DE ANLODIPINO' },
  { nome: 'CLORIDRATO DE BENAZEPRIL' },
  { nome: 'LOSARTANA POTASSICA' },
  { nome: 'VALSARTANA' },
  { nome: 'CANDESARTANA CILEXETILA' },
  { nome: 'TEMOZOLOMIDA' },
  { nome: 'TELMISARTANA' },
  { nome: 'OLMESARTANA MEDOXOMILA' },
  { nome: 'AZILSARTANA MEDOXOMILA' },
  { nome: 'SACUBITRIL' },
  { nome: 'CANDESARTANA' },
  { nome: 'ROSUVASTATINA CALCICA' },
  { nome: 'AGUA PURIFICADA' },
  { nome: 'SINVASTATINA' },
  { nome: 'PITAVASTATINA CALCICA' },
  { nome: 'ATORVASTATINA CALCICA' },
  { nome: 'EVOLOCUMABE' },
  { nome: 'LOVASTATINA' },
  { nome: 'PRAVASTATINA' },
  { nome: 'FLUVASTATINA' },
  { nome: 'ATORVASTATINA' },
  { nome: 'ROSUVASTATINA' },
  { nome: 'BEZAFIBRATO' },
  { nome: 'GENFIBROZILA' },
  { nome: 'FENOFIBRATO' },
  { nome: 'CIPROFIBRATO' },
  { nome: 'COLESEVELAM' },
  { nome: 'ACIDO NICOTINICO' },
  { nome: 'LAROPIPRANTO' },
  { nome: 'EZETIMIBA' },
  { nome: 'OXIDO DE ZINCO' },
  { nome: 'NITRATO DE MICONAZOL' },
  { nome: 'BENZALCONIO' },
  { nome: 'ECONAZOL' },
  { nome: 'CLOTRIMAZOL' },
  { nome: 'MICONAZOL' },
  { nome: 'TIABENDAZOL' },
  { nome: 'TIOCONAZOL' },
  { nome: 'CETOCONAZOL' },
  { nome: 'FENTICONAZOL' },
  { nome: 'SULFETO DE SELENIO' },
  { nome: 'CICLOPIROX OLAMINA' },
  { nome: 'TERBINAFINA' },
  { nome: 'AMOROLFINA' },
  { nome: 'ACIDO BENZOICO' },
  { nome: 'ACIDO PROPIONATO' },
  { nome: 'ACIDO UNDECILENICO' },
  { nome: 'HEXILRESORCINOL' },
  { nome: 'GRISEOFULVINA' },
  { nome: 'UREIA' },
  { nome: 'BISMUTO' },
  { nome: 'OLEO DE PEIXE' },
  { nome: 'ACIDO SALICILICO' },
  { nome: 'ENXOFRE' },
  { nome: 'ACIDO LATICO' },
  { nome: 'ACIDO BORICO' },
  { nome: 'FUCSINA BASICA' },
  { nome: 'IODO' },
  { nome: 'FIBRINOLISINA' },
  { nome: 'DESOXIRRIBONUCLEASE' },
  { nome: 'CLORANFENICOL' },
  { nome: 'ACIDO HIALURONICO' },
  { nome: 'COLAGENASE' },
  { nome: 'MALEATO DE DEXCLORFENIRAMINA' },
  { nome: 'TRICLOSANA' },
  { nome: 'MENTOL' },
  { nome: 'BENZOCAINA' },
  { nome: 'PROMETAZINA' },
  { nome: 'CALAMINA' },
  { nome: 'CANFORA' },
  { nome: 'DIFENIDRAMINA' },
  { nome: 'BENZOLCONIO' },
  { nome: 'CETILPIRIDINIO' },
  { nome: 'MALVA' },
  { nome: 'TINTURA DE MATRICARIA CHAMOMILLA' },
  { nome: 'COALTAR' },
  { nome: 'METOXISALENO' },
  { nome: 'TACROLIMO MONOIDRATADO' },
  { nome: 'RIFAMICINA' },
  { nome: 'RIFAMICINA SV SODICA' },
  { nome: 'SULFATO DE NEOMICINA' },
  { nome: 'BACITRACINA ZINCICA' },
  { nome: 'BACITRACINA' },
  { nome: 'NEOMICINA' },
  { nome: 'MUPIROCINA' },
  { nome: 'SULFADIAZINA DE PRATA' },
  { nome: 'TROMANTADINA' },
  { nome: 'ACICLOVIR' },
  { nome: 'PODOFILOTOXINA' },
  { nome: 'LISOZIMA' },
  { nome: 'IMIQUIMODE' },
  { nome: 'PROPIONATO DE CLOBETASOL' },
  { nome: 'FUROATO DE MOMETASONA' },
  { nome: 'ACEPONATO DE METILPREDNISOLONA' },
  { nome: 'ACETATO DE HIDROCORTISONA' },
  { nome: 'HIDROCORTISONA' },
  { nome: 'CLIOQUINOL' },
  { nome: 'DESONIDA' },
  { nome: 'TRIANCINOLONA' },
  { nome: 'TRIANCINOLONA ACETONIDA' },
  { nome: 'BETAMETASONA' },
  { nome: 'FLUDROXICORTIDA' },
  { nome: 'MOMETASONA' },
  { nome: 'PREDNICARBATO' },
  { nome: 'CLOBETASOL' },
  { nome: 'SULFATO DE GENTAMICINA' },
  { nome: 'DIPROPIONATO DE BETAMETASONA' },
  { nome: 'VALERATO DE BETAMETASONA' },
  { nome: 'TOLNAFTATO' },
  { nome: 'GRAMICIDINA' },
  { nome: 'PREDNISOLONA' },
  { nome: 'BENZOATO DE BENZILA' },
  { nome: 'FLUMETASONA' },
  { nome: 'HIDROQUINONA' },
  { nome: 'FLUOCINOLONA' },
  { nome: 'TRETINOINA' },
  { nome: 'ACIDO FUSIDICO' },
  { nome: 'GENTAMICINA' },
  { nome: 'CLORETO DE BENZETONIO' },
  { nome: 'CLOREXIDINA' },
  { nome: 'IODOPOVIDONA' },
  { nome: 'BENZOXONIO' },
  { nome: 'BENZETONIO' },
  { nome: 'NITRATO DE PRATA' },
  { nome: 'SULFACETAMIDA' },
  { nome: 'TRIETANOLAMINA' },
  { nome: 'CETRIMONIO' },
  { nome: 'CALENDULA OFFICINALIS' },
  { nome: 'ADAPALENO' },
  { nome: 'ISOTRETINOINA' },
  { nome: 'PEROXIDO DE BENZOILA' },
  { nome: 'ACIDO AZELAICO' },
  { nome: 'ALANTOINA' },
  { nome: 'HEPARINA SODICA SUINA' },
  { nome: 'CLORETO DE BENZALCONIO' },
  { nome: 'FLUOCINOLONA ACETONIDA' },
  { nome: 'ACIDO GLICOLICO' },
  { nome: 'ACIDO AMINOBENZOICO' },
  { nome: 'QUERATINA' },
  { nome: 'LEVEDURA' },
  { nome: 'CISTINA' },
  { nome: 'ACIDO PARAMINOBENZOICO' },
  { nome: 'TACROLIMO' },
  { nome: 'MINOXIDIL' },
  { nome: 'FINASTERIDA' },
  { nome: 'OLEO DE ABACATE' },
  { nome: 'ARNICA MONTANA' },
  { nome: 'ATROPA BELLADONNA' },
  { nome: 'MAYTENUS ILICIFOLIA' },
  { nome: 'MIKANIA' },
  { nome: 'GUACO' },
  { nome: 'ALLIUM SATIVUM' },
  { nome: 'MELISSA' },
  { nome: 'PASSIFLORA' },
  { nome: 'NASTURTIUM OFFICINALE' },
  { nome: 'SOLIDAGO MICROGLOSSA' },
  { nome: 'PEUMUS BOLDUS' },
  { nome: 'MENTHA PIPERITA' },
  { nome: 'ECHINACEA' },
  { nome: 'ANANAS CAMOSUS' },
  { nome: 'OPERCULINA ALATA' },
  { nome: 'LUFFA OPERCULATA' },
  { nome: 'HYDRATIS CANADENSIS' },
  { nome: 'HAMAMELIS' },
  { nome: 'GLICYRR HIZA' },
  { nome: 'CINCHONA CALISAYA' },
  { nome: 'CARDUUS MARIANUS' },
  { nome: 'HYPERICUM PERFORATUM' },
  { nome: 'PRUNUS AFRICANA' },
  { nome: 'AESCULUS HIPPOCASTANUM' },
  { nome: 'GINSENG' },
  { nome: 'VALERIANA' },
  { nome: 'TRIFOLIUM PRATENSE' },
  { nome: 'SILYBUM MARIANUM' },
  { nome: 'UNCARIA TOMENTOSA' },
  { nome: 'EMULSAO DE LIPIDEOS' },
  { nome: 'SOLIDAGO VIRGAUREA' },
  { nome: 'GLYCYRRHIZA GLABRA' },
  { nome: 'TANACETUM PARTHENIUM' },
  { nome: 'KAVA-KAVA' },
  { nome: 'HEDERA HELIX' },
  { nome: 'GLYCINE MAX' },
  { nome: 'VITIS VINIFERA' },
  { nome: 'TRITICUM' },
  { nome: 'SERENOA REPENS' },
  { nome: 'CIMICIFUGA RACEMOSA' },
  { nome: 'VALERIANA OFFICINALIS' },
  { nome: 'MATRICARIA' },
  { nome: 'HARPAGOPHYTUM PROCUMBENS' },
  { nome: 'ALCACHOFRA' },
  { nome: 'ALOE VERA' },
  { nome: 'MELILOTUS' },
  { nome: 'BACOPA MONNIERI' },
  { nome: 'RHAMNUS PURSHIANA' },
  { nome: 'POLYPODIUM LEUCOTOMOS' },
  { nome: 'CURCUMA LONGA' },
  { nome: 'CASTANHA DA INDIA' },
  { nome: 'SAW PALMETO' },
  { nome: 'CASSIA SENNA' },
  { nome: 'BOSWELLA SERRATA' },
  { nome: 'SYMPHYTUM OFFICINALE' },
  { nome: 'VITEX AGNUS CASTUS' },
  { nome: 'RHODIOLA ROSEAL' },
  { nome: 'BROSIMUN GAUDICHAUDII' },
  { nome: 'CORDIA VERBENACEA' },
  { nome: 'PINUS PINASTER' },
  { nome: 'CEREUS JAMACARU' },
  { nome: 'ASSOCIACOES' },
  { nome: 'QUITOSANA' },
  { nome: 'STRYPHNODENADRON ADSTRINGENS' },
  { nome: 'HUMULUS LUPULUS' },
  { nome: 'ORIZA SATIVA' },
  { nome: 'SCHINUS TEREBINTHIFOLIUS RADDI' },
  { nome: 'CENTELLA ASIATICA' },
  { nome: 'SENE' },
  { nome: 'PIPER METHYSTICUM' },
  { nome: 'BORAGO OFICINALIS L.' },
  { nome: 'TRIBULUS TERRESTRIS' },
  { nome: 'EUPHORBIUM' },
  { nome: 'URTICA DIOICA' },
  { nome: 'PYGEUM AFRICANUM' },
  { nome: 'BOLDO' },
  { nome: 'SEMENTE DE PLANTAGO' },
  { nome: 'BRINZOLAMIDA' },
  { nome: 'TIMOLOL' },
  { nome: 'CASSIA' },
  { nome: 'CORIANDRUM' },
  { nome: 'GLYCYRRHIZA' },
  { nome: 'SENNA' },
  { nome: 'TAMARINDUS' },
  { nome: 'ALCACUZ' },
  { nome: 'CASSIA FISTULA' },
  { nome: 'CORIANDRUM SATIVUM' },
  { nome: 'SENA' },
  { nome: 'VACCINIUM MACROCARPON' },
  { nome: 'BORAGO OFFICINALIS' },
  { nome: 'MERCURIUS CYANATUS' },
  { nome: 'PETASITES HYBRIDUS' },
  { nome: 'VINCETOXICUM HIRUNDINARIA' },
  { nome: 'ACONITUM NAPELLUS' },
  { nome: 'SANGUINARIA CANADENSIS' },
  { nome: 'MYOSOTIS ARVENSIS' },
  { nome: 'ACIDUM PHOSPHORICUM' },
  { nome: 'CITRULLUS COLOCYNTHIS' },
  { nome: 'ANAMIRTA COCCULUS' },
  { nome: 'RHUS TOXICODENDRON' },
  { nome: 'CRATAEGUS' },
  { nome: 'SALIX' },
  { nome: 'AESCULUS' },
  { nome: 'POLYGONUM' },
  { nome: 'RUTINA' },
  { nome: 'SMILAX' },
  { nome: 'PLUMERIA LANCIFOLIA' },
  { nome: 'SALICILATO DE SODIO' },
  { nome: 'CASCARA SAGRADA' },
  { nome: 'CHAMOMILLA' },
  { nome: 'MARACUJA' },
  { nome: 'MULUNGA' },
  { nome: 'ALOES' },
  { nome: 'IPECA' },
  { nome: 'ALOINA' },
  { nome: 'ERVA DE BICHO' },
  { nome: 'ADONIS VERNALIS' },
  { nome: 'OXYACANTHA' },
  { nome: 'CASSIA ANGUSTIFOLIA' },
  { nome: 'ROSA SILVESTRE' },
  { nome: 'NUX VOMICA' },
  { nome: 'BERBERIS VULGARIS' },
  { nome: 'ASSOCICAO' },
  { nome: 'PELARGONIUM SIDOIDES' },
  { nome: 'GLICEROFOSFATO DE CALCIO' },
  { nome: 'GLICEROFOSFATO DE SODIO' },
  { nome: 'COLA' },
  { nome: 'ARSENUN IODATUM' },
  { nome: 'TINIDAZOL' },
  { nome: 'BENZOILMETRONIDAZOL' },
  { nome: 'CLORETO DE BENZALCONICO' },
  { nome: 'ANFOTERICINA B' },
  { nome: 'TETRACICLINA' },
  { nome: 'CLORIDRATO DE TETRACICLINA' },
  { nome: 'MEPARTRICINA' },
  { nome: 'HIDROXIQUINOLINA' },
  { nome: 'TIROTRICINA' },
  { nome: 'TIROTRICINA ASSOCIADA' },
  { nome: 'METRONIDAZOL' },
  { nome: 'ISOCONAZOL' },
  { nome: 'TERCONAZOL' },
  { nome: 'NITRATO DE FENTICONAZOL' },
  { nome: 'NITRATO DE BUTOCONAZOL' },
  { nome: 'NONOXINOL' },
  { nome: 'RITODRINA' },
  { nome: 'ATOSIBANA' },
  { nome: 'ETINILESTRADIOL' },
  { nome: 'DESOGESTREL' },
  { nome: 'GESTODENO' },
  { nome: 'LEVONORGESTREL' },
  { nome: 'ACETATO DE CLORMADINONA' },
  { nome: 'ACETATO DE CIPROTERONA' },
  { nome: 'DROSPIRENONA' },
  { nome: 'CLATRATO DE ETINILESTRADIOL BETACICLODEXTRINA' },
  { nome: 'VALERATO DE ESTRADIOL' },
  { nome: 'DIENOGESTE' },
  { nome: 'NORGESTIMATO' },
  { nome: 'ETONOGESTREL' },
  { nome: 'ACETATO DE MEDROXIPROGESTERONA' },
  { nome: 'ENANTATO DE ESTRADIOL' },
  { nome: 'ALGESTONA ACETOFENIDA' },
  { nome: 'CIPIONATO DE ESTRADIOL' },
  { nome: 'ENANTATO DE NORETISTERONA' },
  { nome: 'NORETISTERONA' },
  { nome: 'ESTRADIOL' },
  { nome: 'NORGESTREL' },
  { nome: 'ESTROGENIOS CONJUGADOS' },
  { nome: 'MEDROXIPROGESTERONA' },
  { nome: 'NOMEGESTROL' },
  { nome: 'CLORMADINONA' },
  { nome: 'MEGESTROL' },
  { nome: 'ULIPRISTAL' },
  { nome: 'TESTOSTERONA' },
  { nome: 'ESTRADIOL HEMI-HIDRATADO' },
  { nome: 'ESTRIOL' },
  { nome: 'PROMESTRIENO' },
  { nome: 'TRIMEGESTONA' },
  { nome: 'ALGESTONA' },
  { nome: 'HIDROXIPROGESTERONA' },
  { nome: 'ESTRONA' },
  { nome: 'TIBOLONA' },
  { nome: 'ACETATO DE NOMEGESTROL' },
  { nome: 'LINESTRENOL' },
  { nome: 'ACETATO DE NORETISTERONA' },
  { nome: 'DIDROGESTERONA' },
  { nome: 'ALFACORIOGONADOTROPINA' },
  { nome: 'GONADOTROPINA CORIONICA' },
  { nome: 'UROFOLITROPINA' },
  { nome: 'ALFAFOLITROPINA' },
  { nome: 'MENOTROPINA' },
  { nome: 'GONADOTROPINA MENOPAUSICA' },
  { nome: 'CICLOFENILA' },
  { nome: 'CLOMIFENO' },
  { nome: 'CIPROTERONA' },
  { nome: 'GESTRINONA' },
  { nome: 'METENAMINA' },
  { nome: 'CLORETO DE METILTIONINIO' },
  { nome: 'OXIBUTININA' },
  { nome: 'TOLTERODINA' },
  { nome: 'DARIFENACINA' },
  { nome: 'ALPROSTADIL' },
  { nome: 'SILDENAFILA' },
  { nome: 'TADALAFILA' },
  { nome: 'VARDENAFILA' },
  { nome: 'PAPAVERINA' },
  { nome: 'QUININA' },
  { nome: 'FENAZOPIRIDINA' },
  { nome: 'DAPOXETINA' },
  { nome: 'DUTASTERIDA' },
  { nome: 'CLORIDRATO DE TANSULOSINA' },
  { nome: 'TANSULOSINA' },
  { nome: 'TERAZOSINA' },
  { nome: 'SILODOSINA' },
  { nome: 'CLORIDRATO DE VARDENAFILA' },
  { nome: 'CARBONATO DE LODENAFILA' },
  { nome: 'SOMATROPINA' },
  { nome: 'DESMOPRESSINA' },
  { nome: 'OCITOCINA' },
  { nome: 'CARBETOCINA' },
  { nome: 'DIASPARTATO DE PASIREOTIDA' },
  { nome: 'NAFARRELINA' },
  { nome: 'OCTREOTIDA' },
  { nome: 'SUCCINATO SODICO DE HIDROCORTISONA' },
  { nome: 'TRIANCINOLONA HEXACETONIDA' },
  { nome: 'ACETATO DE METILPREDNISOLONA' },
  { nome: 'FOSFATO DISSODICO DE BETAMETASONA' },
  { nome: 'FOSFATO SODICO DE PREDNISOLONA' },
  { nome: 'FLUDROCORTISONA' },
  { nome: 'FOSFATO DISSODICO DE DEXAMETASONA' },
  { nome: 'METILPREDNISOLONA' },
  { nome: 'PREDNISOLONA, FOSFATO SODICO' },
  { nome: 'PREDNISONA' },
  { nome: 'DEFLAZACORTE' },
  { nome: 'LEVOTIROXINA' },
  { nome: 'PROPILTIOURACIL' },
  { nome: 'GLUCAGON' },
  { nome: 'CLORIDRATO DE CINACALCETE' },
  { nome: 'RAMELTEONA' },
  { nome: 'TERIPARATIDA' },
  { nome: 'CALCITONINA SINTETICA DE SALMAO' },
  { nome: 'PARICALCITOL' },
  { nome: 'CIPROFLOXACINO' },
  { nome: 'ACIDO NALIDIXICO' },
  { nome: 'NITROFURANTOINA' },
  { nome: 'ACETATO DE CASPOFUNGINA' },
  { nome: 'FLUCONAZOL' },
  { nome: 'ITRACONAZOL' },
  { nome: 'VORICONAZOL' },
  { nome: 'CASPOFUNGINA' },
  { nome: 'ANIDULAFUNGINA' },
  { nome: 'SULFATO DE ESTREPTOMICINA' },
  { nome: 'DICLORIDRATO DE ETAMBUTOL' },
  { nome: 'ETIONAMIDA' },
  { nome: 'PIRAZINAMIDA' },
  { nome: 'RIBAVIRINA' },
  { nome: 'GANCICLOVIR' },
  { nome: 'FANCICLOVIR' },
  { nome: 'SAQUINAVIR' },
  { nome: 'INDINAVIR' },
  { nome: 'RITONAVIR' },
  { nome: 'NELFINAVIR' },
  { nome: 'AMPRENAVIR' },
  { nome: 'DARUNAVIR' },
  { nome: 'ZIDOVUDINA' },
  { nome: 'DIDANOSINA' },
  { nome: 'ESTAVUDINA' },
  { nome: 'LAMIVUDINA' },
  { nome: 'TELBIVUDINA' },
  { nome: 'NEVIRAPINA' },
  { nome: 'EFAVIRENZ' },
  { nome: 'ETRAVIRINA' },
  { nome: 'TENOFOVIR' },
  { nome: 'DASABUVIR' },
  { nome: 'OMBITASVIR' },
  { nome: 'VERUPREVIR' },
  { nome: 'DACLATASVIR' },
  { nome: 'ALFAPEGINTERFERONA 2B' },
  { nome: 'ALFAPEGINTERFERONA 2A' },
  { nome: 'CLORIDRATO DE VALACICLOVIR' },
  { nome: 'FUMARATO DE TENOFOVIR DESOPROXILA' },
  { nome: 'ENTRICITABINA' },
  { nome: 'SULFATO DE ATAZANAVIR' },
  { nome: 'LOPINAVIR' },
  { nome: 'DOLUTEGRAVIR SODICO' },
  { nome: 'RALTEGRAVIR POTASSICO' },
  { nome: 'SULFATO DE ABACAVIR' },
  { nome: 'IMUNOGLOBULINA HUMANA' },
  { nome: 'IMUNOGLOBULINA G' },
  { nome: 'IMUNOGLOBULINA ANTITIMOCITOS' },
  { nome: 'IMUNOGLOBULINA ANTI-RHO(D)' },
  { nome: 'IMUNOGLOBULINA ANTITETANICA' },
  { nome: 'IMUNOGLOBULINA ANTI-CITOMEGALOVIRUS' },
  { nome: 'IMUNOGLOBULINA HUMANA NORMAL' },
  { nome: 'IMUNOGLOBULINAS' },
  { nome: 'IMUNOGLOBULINA HUMANA ANTI-HEPATITE B' },
  { nome: 'VACINA CONTRA DIFTERIA, TETANO E COQUELUCHE' },
  { nome: 'CEPAS DE VIRUS INFLUENZA FRAGMENTADO E INATIVO (H1N1' },
  { nome: 'H3N2' },
  { nome: 'VICTORIA' },
  { nome: 'YAMAGATA)' },
  { nome: 'CEPAS DE VIRUS INFLUENZA FRAGMENTADO E INATIVADO (H1N1' },
  { nome: 'VACINA MENINGOCOCICA' },
  { nome: 'VACINA CONTRA MENINGOCOCICA A' },
  { nome: 'C' },
  { nome: 'VACINA CONTRA MENINGOCOCICA C' },
  { nome: 'VACINA PNEUMOCOCICA' },
  { nome: 'VACINA PNEUMO' },
  { nome: 'HEMOFILOS' },
  { nome: 'TOXINA TETANICA' },
  { nome: 'VACINA FEBRE TIFOIDE' },
  { nome: 'ANTIGENOS BACTERIANOS POLIVALENTES' },
  { nome: 'VACINAS DIVERSAS' },
  { nome: 'VACINA DTPA' },
  { nome: 'VACINA CONTRA SARAMPO, CAXUMBA E RUBEOLA' },
  { nome: 'LISADO BACTERIANO' },
  { nome: 'TOXOIDE DIFTERICO' },
  { nome: 'TOXOIDE TETANICO' },
  { nome: 'POLISSACARIDEO DE HAEMOPHILUS INFLUENZAE TIPO B' },
  { nome: 'PERTUSSIS CELULAR' },
  {
    nome:
      'VACINA ADSORVIDA DIFTERIA, TETANO, PERTUSSIS (ACELULAR), POLIOMIELITE 1, 2 E 3 (INATIVADA) E HAEMOPHILUS INFLUENZAE B (CONJUGADA)',
  },
  {
    nome:
      'VACINA ADSORVIDA DIFTERIA, TETANO, PERTUSSIS (ACELULAR), POLIOMIELITE 1, 2 E 3 (INATIVADA)',
  },
  { nome: 'TOXOIDE PERTUSSIS' },
  { nome: 'PERTACTINA' },
  { nome: 'HEMAGLUTININA FILAMENTOSA' },
  {
    nome: 'AGLUTINOGENOS FIMBRIAIS DE BORDETELLA PERTUSSIS DOS SOROTIPOS 2 E 3',
  },
  {
    nome:
      'VACINA ADSORVIDA CONTRA DIFTERIA, TETANO, COQUELUCHE ACELULAR, POLIOMIELITE INATIVADA, HEPATITE B (RECOMBINANTE) E HAEMOPHILUS INFLUENZAE TIPO B CONJUGADO',
  },
  { nome: 'VACINA ADSORVIDA DIFTERIA, TETANO E PERTUSSIS (ACELULAR)' },
  { nome: 'ANTIGENO PERTUSSIS' },
  { nome: 'ANATOXINA TETANICA' },
  { nome: 'ANATOXINA DIFTERICA' },
  { nome: 'VACINA SARAMPO (ATENUADA)' },
  { nome: 'VACINA SARAMPO, CAXUMBA, RUBEOLA E VARICELA (ATENUADA)' },
  { nome: 'VIRUS DO SARAMPO' },
  { nome: 'VIRUS DA RUBEOLA' },
  { nome: 'VIRUS DA CAXUMBA' },
  { nome: 'VIRUS DA VARICELA' },
  { nome: 'VACINA VIRUS INFLUENZA INATIVADA' },
  { nome: 'VACINA INFLUENZA (INATIVADA)' },
  { nome: 'VACINA VIRUS INFLUENZA H1N1' },
  { nome: 'VACINA CONTRA GRIPE' },
  { nome: 'VACINA CONJUGADA CONTRA HAEMOPHILUS INFUENZAE TIPO B (HIB)' },
  { nome: 'VACINA CONTRA HEPATITE A E B' },
  { nome: 'ANTIGENO DE SUPERFICIE DA HEPATITE B' },
  { nome: 'VACINA CONTRA HEPATITE B' },
  { nome: 'VACINA HEPATITE B (RECOMBINANTE)' },
  { nome: 'VACINA CONTRA HEPATITE A' },
  { nome: 'VACINA CONTRA SARAMPO' },
  { nome: 'CAXUMBA' },
  { nome: 'RUBEOLA' },
  { nome: 'VARICELA' },
  { nome: 'VACINA CONTRA CAXUMBA' },
  { nome: 'VACINA CONTRA POLIOMIELITE' },
  { nome: 'VACINA ANTI-RABICA' },
  { nome: 'VACINA CONTRA ROTAVIRUS' },
  { nome: 'VACINA CONTRA VARICELA' },
  { nome: 'VACINA ZOSTER VIVO' },
  { nome: 'VACINA FEBRE AMARELA' },
  { nome: 'VACINA CONTRA PAPILOMAVIRUS' },
  { nome: 'VACINA CONTRA HPV' },
  { nome: 'POLISSACARIDEO CAPSULAR DE STREPTOCOCCUS PNEUMONIAE' },
  { nome: 'VACINA PNEUMOCOCICA 10-VALENTE (CONJUGADA)' },
  { nome: 'VACINA PNEUMOCOCICA 13-VALENTE (CONJUGADA)' },
  { nome: 'POLISSACARIDEO N. MENINGITIDIS TIPO C' },
  { nome: 'POLISSACARIDEO N. MENINGITIDIS TIPO A' },
  { nome: 'VACINA MENINGOCOCICA ACWY (CONJUGADA)' },
  {
    nome:
      'VESICULAS DE MEMBRANA EXTERNA (OMV) DE NEISSERIA MENINGITIDIS DO SOROGRUPO B',
  },
  {
    nome:
      'PROTEINA DE FUSAO NHBA RECOMBINANTE DE NEISSERIA MENINGITIDIS DO SOROGRUPO B',
  },
  {
    nome:
      'PROTEINA DE FUSAO NAD RECOMBINANTE DE NEISSERIA MENINGITIDIS DO SOROGRUPO B',
  },
  { nome: 'PROTEINA NAD A RECOMBINAN' },
  { nome: 'VACINA MENINGOGOCICA CONJUGADA DO GRUPO C' },
  { nome: 'CEPA INFLUENZA TIPO A (H3N2)' },
  { nome: 'CEPA INFLUENZA TIPO A (H1N1)' },
  { nome: 'CEPA INFLUENZA TIPO B' },
  { nome: 'PARTICULA SEMELHANTE A VIRUS DE PROTEINA L1 DO HPV DO TIPO 6' },
  { nome: 'PARTICULA SEMELHANTE A VIRUS DE PROTEINA L1 DO HPV DO TIPO 18' },
  { nome: 'PARTICULA SEMELHANTE A VIRUS DE PROTEINA L1 DO HPV DO TIPO 16' },
  { nome: 'PARTICULA SEMELHANTE A VIRUS DE PROTEINA L1 DO HPV DO TIPO 11' },
  { nome: 'VACINA ADSORVIDA HEPATITE A (INATIVADA)' },
  { nome: 'PROTEINA ANTIGENICA DE SUPERFICIE (HEP. B)' },
  { nome: 'VIRUS DA HEPATITE A PURIFICADO INATIVADO' },
  { nome: 'ROTAVIRUS HUMANO ATENUADO' },
  { nome: 'VACINA FEBRE AMARELA (ATENUADA)' },
  { nome: 'VIRUS QUIMERICO FEBRE AMARELA – DENGUE SOROTIPO 4' },
  { nome: 'VIRUS QUIMERICO FEBRE AMARELA – DENGUE SOROTIPO 3' },
  { nome: 'VIRUS QUIMERICO FEBRE AMARELA – DENGUE SOROTIPO 2' },
  { nome: 'VIRUS QUIMERICO FEBRE AMARELA – DENGUE SOROTIPO 1' },
  {
    nome:
      'VACINA POLIOMIELITE 1, 2 E 3 (INATIVADA)VACINA CONTRA POLIOMELITE INATIVADA',
  },
  { nome: 'POLIOVIRUS TIPO 3' },
  { nome: 'POLIOVIRUS TIPO 2' },
  { nome: 'POLIOVIRUS TIPO 1' },
  { nome: 'VIRUS RABICO INATIVADO' },
  { nome: 'VACINA CONTRA RAIVA' },
  {
    nome:
      'LISADOS BACTERIANOS (STAPHYLOCOCCUS AUREUS, STREPTOCOCCUS PYOGENES, STREPTOCOCCUS MITIS, STREPTOCOCCUS PNEUMONIAE,KLEBSIELLA PNEUMONIAE, BRANHAMELLA CATARRHALIS, HAEMOPHILUS INFLUENZAE)',
  },
  { nome: 'GLICOSE ANIDRA' },
  { nome: 'GLICONATO DE SODIO' },
  { nome: 'CLORETO DE MAGNESIO HEXAIDRATADO' },
  { nome: 'ACETATO DE SODIO TRIHIDRATADO' },
  { nome: 'ACETATO DE SODIO TRI-HIDRATADO' },
  { nome: 'FOSFATO DE POTASSIO DIBASICO' },
  { nome: 'DEXTROSE ANIDRA' },
  { nome: 'OLEO DE SOJA' },
  { nome: 'OLEO DE OLIVA' },
  { nome: 'TRIGLICERIDEOS CADEIA MEDIA' },
  { nome: 'LEUCINA' },
  { nome: 'ACIDO GLUTAMICO' },
  { nome: 'ACIDO ASPARTICO' },
  { nome: 'TIROSINA' },
  { nome: 'SERINA' },
  { nome: 'PROLINA' },
  { nome: 'LEVOVALINA' },
  { nome: 'ISOLEUCINA' },
  { nome: 'HISTIDINA' },
  { nome: 'FENILALANINA' },
  { nome: 'ALANINA' },
  { nome: 'ACETATO DE LISINA' },
  { nome: 'ALANILGLUTAMINA' },
  { nome: 'SUCCINILGELATINA' },
  { nome: 'SULFATO DE MAGNESIO HEPTAIDRATADO' },
  { nome: 'GLICOSE MONOHIDRATADA' },
  { nome: 'GLICOSE MONOIDRATADA' },
  { nome: 'ICODEXTRINA' },
  { nome: 'BENDAMUSTINA' },
  { nome: 'CICLOFOSFAMIDA MONOIDRATADA' },
  { nome: 'CICLOFOSFAMIDA' },
  { nome: 'CLORAMBUCILA' },
  { nome: 'MELFALANA' },
  { nome: 'IFOSFAMIDA' },
  { nome: 'BUSSULFANO' },
  { nome: 'CARMUSTINA' },
  { nome: 'DACARBAZINA' },
  { nome: 'CLORIDRATO DE GENCITABINA' },
  { nome: 'TIOGUANINA' },
  { nome: 'MERCAPTOPURINA' },
  { nome: 'METOTREXATO' },
  { nome: 'RALTITREXATO' },
  { nome: 'PEMETREXEDE' },
  { nome: 'FLUDARABINA' },
  { nome: 'CITARABINA' },
  { nome: 'FLUORURACILA' },
  { nome: 'CAPECITABINA' },
  { nome: 'AZACITIDINA' },
  { nome: 'DECITABINA' },
  { nome: 'TEGAFUR' },
  { nome: 'URACILA' },
  { nome: 'SULFATO DE VIMBLASTINA' },
  { nome: 'CABAZITAXEL' },
  { nome: 'CLORIDRATO DE IRINOTECANO' },
  { nome: 'ETOPOSIDEO' },
  { nome: 'ETOPOSIDO' },
  { nome: 'VIMBLASTINA' },
  { nome: 'VINCRISTINA' },
  { nome: 'VINORELBINA' },
  { nome: 'PACLITAXEL' },
  { nome: 'DOCETAXEL' },
  { nome: 'TRABECTEDINA' },
  { nome: 'CLORIDRATO DE IDARRUBICINA' },
  { nome: 'CLORIDRATO DE DAUNORRUBICINA' },
  { nome: 'DACTINOMICINA' },
  { nome: 'DOXORRUBICINA' },
  { nome: 'DAUNORRUBICINA' },
  { nome: 'EPIRRUBICINA' },
  { nome: 'MITOXANTRONA' },
  { nome: 'BLEOMICINA' },
  { nome: 'ESILATO DE NINTEDANIBE' },
  { nome: 'MESILATO DE IMATINIBE' },
  { nome: 'CLORIDRATO DE PAZOPANIBE' },
  { nome: 'DITOSILATO DE LAPATINIBE' },
  { nome: 'CLORIDRATO DE AMINOLEVULINATO DE METILA' },
  { nome: 'AFLIBERCEPTE' },
  { nome: 'OLAPARIBE' },
  { nome: 'PEGASPARGASE' },
  { nome: 'CISPLATINA' },
  { nome: 'CARBOPLATINA' },
  { nome: 'OXALIPLATINA' },
  { nome: 'TRASTUZUMABE' },
  { nome: 'ALENTUZUMABE' },
  { nome: 'PANITUMUMABE' },
  { nome: 'TRASTUZUMABE ENTANSINA' },
  { nome: 'NIVOLUMABE' },
  { nome: 'DARATUMUMABE' },
  { nome: 'RAMUCIRUMABE' },
  { nome: 'PEMBROLIZUMABE' },
  { nome: 'OFATUMUMABE' },
  { nome: 'BLINATUMOMABE' },
  { nome: 'ACIDO AMINOLEVULINICO' },
  { nome: 'IMATINIBE' },
  { nome: 'NILOTINIBE' },
  { nome: 'ASPARAGINASE' },
  { nome: 'HIDROXIUREIA' },
  { nome: 'TOPOTECANO' },
  { nome: 'IRINOTECANO' },
  { nome: 'BORTEZOMIDE' },
  { nome: 'BORTEZOMIBE' },
  { nome: 'ACETATO DE LEUPRORRELINA' },
  { nome: 'LEUPRORRELINA' },
  { nome: 'TRIPTORELINA' },
  { nome: 'CITRATO DE TAMOXIFENO' },
  { nome: 'ACETATO DE DEGARELIX' },
  { nome: 'TAMOXIFENO' },
  { nome: 'FULVESTRANTO' },
  { nome: 'FLUTAMIDA' },
  { nome: 'BICALUTAMIDA' },
  { nome: 'ENZALUTAMIDA' },
  { nome: 'ANASTROZOL' },
  { nome: 'LETROZOL' },
  { nome: 'PEGFILGRASTIM' },
  { nome: 'GLICANA' },
  { nome: 'TIMOSTIMULINA' },
  { nome: 'TIMOMODULINA' },
  { nome: 'FILGRASTIM' },
  { nome: 'MOLGRAMOSTINA' },
  { nome: 'LENOGRASTIMA' },
  { nome: 'INTERFERONA ALFA 2A' },
  { nome: 'INTERFERONA ALFA 2B' },
  { nome: 'PEGINTERFERON ALFA-2B' },
  { nome: 'OPRELVECINA' },
  { nome: 'BACILO CALMETTE' },
  { nome: 'VACINA BCG' },
  { nome: 'MIFAMURTIDA' },
  { nome: 'ORTHOCLONE OKT-3' },
  { nome: 'ACIDO MICOFENOLICO' },
  { nome: 'MICOFENOLATO DE MOFETILA' },
  { nome: 'LEFLUNOMIDA' },
  { nome: 'EVEROLIMO' },
  { nome: 'BELATACEPTE' },
  { nome: 'ETANERCEPTE' },
  { nome: 'ETARNECEPTE' },
  { nome: 'INFLIXIMABE' },
  { nome: '' },
  { nome: 'GOLIMUMABE' },
  { nome: 'DACLIZUMABE' },
  { nome: 'TOCILIZUMABE' },
  { nome: 'CICLOSPORINA' },
  { nome: 'AZATIOPRINA' },
  { nome: 'TALIDOMIDA' },
  { nome: 'CERTOLIZUMABE PEGOL' },
  { nome: 'USTEQUINUMABE' },
  { nome: 'CANAQUINUMABE' },
  { nome: 'ECULIZUMABE' },
  { nome: 'MICOFENOLATO DE SODIO' },
  { nome: 'DICLOFENACO' },
  { nome: 'NAPROXENO SODICO' },
  { nome: 'LOXOPROFENO SODICO' },
  { nome: 'CETOPROFENO' },
  { nome: 'FENILBUTAZONA' },
  { nome: 'DICLOFENACO SODICO' },
  { nome: 'DICLOFENACO POTASSIO' },
  { nome: 'DICLOFENACO RESINATO' },
  { nome: 'DICLOFENACO COLESTIRAMINA' },
  { nome: 'DICLOFENACO POTASSICO' },
  { nome: 'DICLOFENACO DIETILAMONIO' },
  { nome: 'ETODOLACO' },
  { nome: 'TROMETAMINA' },
  { nome: 'CETOROLACO TROMETAMOL' },
  { nome: 'TROMETAMOL' },
  { nome: 'ACECLOFENACO' },
  { nome: 'PIROXICAM' },
  { nome: 'TENOXICAM' },
  { nome: 'MELOXICAM' },
  { nome: 'IBUPROFENO' },
  { nome: 'NAPROXENO' },
  { nome: 'FENOPROFENO' },
  { nome: 'FLURBIPROFENO' },
  { nome: 'ACIDO MEFENAMICO' },
  { nome: 'CELECOXIB' },
  { nome: 'CELECOXIBE' },
  { nome: 'CONDROITINA' },
  { nome: 'GLICOSAMINA' },
  { nome: 'BENZIDAMINA' },
  { nome: 'NIMESULIDA' },
  { nome: 'NILUTAMIDA' },
  { nome: 'DIACEREINA' },
  { nome: 'IBUPROFENO ARGININA' },
  { nome: 'CITRATO DE TOFACITINIBE' },
  { nome: 'SALICILATO DE METILA' },
  { nome: 'TEREBENTINA' },
  { nome: 'ETOFENAMATO' },
  { nome: 'CAPSAICINA' },
  { nome: 'BALSAMO DE PERU' },
  { nome: 'CLORETO DE SUXAMETONIO' },
  { nome: 'TOXINA BOTULINICA A' },
  { nome: 'BESILATO DE CISATRACURIO' },
  { nome: 'PANCURONIO' },
  { nome: 'BROMETO DE PANCURONIO' },
  { nome: 'VECURONIO' },
  { nome: 'ATRACURIO' },
  { nome: 'ROCURONIO' },
  { nome: 'CLORIDRATO DE CICLOBENZAPRINA' },
  { nome: 'CLONIXINATO DE LISINA' },
  { nome: 'CARISOPRODOL' },
  { nome: 'CAFEINA' },
  { nome: 'CITRATO DE ORFENADRINA' },
  { nome: 'CICLOBENZAPRINA' },
  { nome: 'BACLOFENO' },
  { nome: 'TIOCOLCHICOSIDEO' },
  { nome: 'ALOPURINOL' },
  { nome: 'BENZBROMARONA' },
  { nome: 'COLCHICINA' },
  { nome: 'IBANDRONATO DE SODIO' },
  { nome: 'ALENDRONATO DE SODIO TRI-HIDRATADO' },
  { nome: 'ACIDO CLODRONICO' },
  { nome: 'PAMIDRONATO' },
  { nome: 'ALENDRONATO DE SODIO' },
  { nome: 'IBANDRONATO' },
  { nome: 'RISEDRONATO SODICO' },
  { nome: 'RESIDRONATO DE SODIO' },
  { nome: 'ACIDO ZOLEDRONICO' },
  { nome: 'IPRIFLAVONA' },
  { nome: 'DENOSUMABE' },
  { nome: 'SULFATO DE GLICOSAMINA' },
  { nome: 'SULFATO DE CONDROITINA' },
  { nome: 'QUIMOTRIPSINA' },
  { nome: 'TRIPSINA' },
  { nome: 'HILANO G-F20' },
  { nome: 'HIALURONATO DE SODIO' },
  { nome: 'CITRATO DE FENTANILA' },
  { nome: 'DROPERIDOL' },
  { nome: 'CLORIDRATO DE DEXMEDETOMIDINA' },
  { nome: 'CLORIDRATO DE REMIFENTANILA' },
  { nome: 'CLORIDRATO DE MIDAZOLAM' },
  { nome: 'CITRATO DE SUFENTANILA' },
  { nome: 'CLORIDRATO DE DEXTROCETAMINA' },
  { nome: 'ENFLURANO' },
  { nome: 'ISOFLURANO' },
  { nome: 'TIOPENTAL SODICO' },
  { nome: 'FENTANILA' },
  { nome: 'SUFENTANILA' },
  { nome: 'CETAMINA' },
  { nome: 'ETOMIDATO' },
  { nome: 'PROPOFOL' },
  { nome: 'CLORIDRATO DE BUPIVACAINA' },
  { nome: 'CLORIDRATO DE MEPIVACAINA' },
  { nome: 'TETRACAINA' },
  { nome: 'BUPIVACAINA' },
  { nome: 'MEPIVACAINA' },
  { nome: 'ROPIVACAINA' },
  { nome: 'ROPINIROL' },
  { nome: 'LEVOBUPIVACAINA' },
  { nome: 'NORAEPINEFRINA' },
  { nome: 'CORBADRINA' },
  { nome: 'FELIPRESSINA' },
  { nome: 'ARTICAINA' },
  { nome: 'SULFATO DE MORFINA' },
  { nome: 'SULFATO DE MORFINA PENTAIDRATADA' },
  { nome: 'CLORIDRATO DE OXICODONA' },
  { nome: 'CLORIDRATO DE METADONA' },
  { nome: 'CLORIDRATO DE TRAMADOL' },
  { nome: 'CLORIDRATO DE PETIDINA' },
  { nome: 'FOSFATO DE CODEINA' },
  { nome: 'MORFINA' },
  { nome: 'HIDROMORFONA' },
  { nome: 'CODEINA' },
  { nome: 'FENILTOLOXAMINA' },
  { nome: 'GUAIFENESINA' },
  { nome: 'FONETILAMINA' },
  { nome: 'PENTETRAZOL' },
  { nome: 'PETIDINA' },
  { nome: 'BUPRENORFINA' },
  { nome: 'TRAMADOL' },
  { nome: 'TAPENTADOL' },
  { nome: 'CLORIDRATO DE PROMETAZINA' },
  { nome: 'CLORIDRATO DE ADIFENINA' },
  { nome: 'PROPIFENAZONA' },
  { nome: 'MUCATO DE ISOMETEPTENO' },
  { nome: 'HIDROXIBENZOATO DE VIMINOL' },
  { nome: 'DEXCLORFENIRAMINA' },
  { nome: 'FENILEFRINA' },
  { nome: 'ISOSSORBIDA' },
  { nome: 'CLORFENIRAMINA' },
  { nome: 'DEXTROPROPOXIFENO' },
  { nome: 'MEPIRAMINA' },
  { nome: 'ORFENADRINA' },
  { nome: 'ISOMETEPTENO' },
  { nome: 'ASSOC.' },
  { nome: 'HIOSCIAMINA' },
  { nome: 'CLOROFILA' },
  { nome: 'EUCALIPTOL' },
  { nome: 'TERPINEOL' },
  { nome: 'ADIFENINA' },
  { nome: 'BRONFENIRAMINA' },
  { nome: 'PSEUDOEFEDRINA' },
  { nome: 'DIIDROERGOTAMINA' },
  { nome: 'ERGOTAMINA' },
  { nome: 'CARBINOXAMINA' },
  { nome: 'PIRILAMINA' },
  { nome: 'OXOMEMAZINA' },
  { nome: 'SUCCINATO DE SUMATRIPTANA' },
  { nome: 'CLORIDRATO DE NARATRIPTANA' },
  { nome: 'METISERGIDA' },
  { nome: 'NARATRIPTANA' },
  { nome: 'ZOLMITRIPTANO' },
  { nome: 'PERAMPANEL' },
  { nome: 'RUFINAMIDA' },
  { nome: 'FENOBARBITAL SODICO' },
  { nome: 'FENOBARBITAL' },
  { nome: 'FENITOINA' },
  { nome: 'DIAZEPAM' },
  { nome: 'CLONAZEPAM' },
  { nome: 'CARBAMAZEPINA' },
  { nome: 'OXCARBAZEPINA' },
  { nome: 'DIVALPROATO SODIO' },
  { nome: 'ACIDO VALPROICO' },
  { nome: 'VALPROATO DE SODIO' },
  { nome: 'DIVALPROATO DE SODIO' },
  { nome: 'LAMOTRIGINA' },
  { nome: 'TOPIRAMATO' },
  { nome: 'GABAPENTINA' },
  { nome: 'PREGABALINA' },
  { nome: 'LACOSAMIDA' },
  { nome: 'DICLORIDRATO DE PRAMIPEXOL MONOIDRATADO' },
  { nome: 'DICLORIDRATO DE PRAMIPEXOL' },
  { nome: 'LEVODOPA' },
  { nome: 'CLORIDRATO DE BIPERIDENO' },
  { nome: 'CLORIDRATO DE BENSERAZIDA' },
  { nome: 'CARBIDOPA' },
  { nome: 'LACTATO DE BIPERIDENO' },
  { nome: 'BIPERIDENO' },
  { nome: 'BENSERAZINA' },
  { nome: 'PRAMIPEXOL' },
  { nome: 'SELEGILINA' },
  { nome: 'CLORIDRATO DE SELEGILINA' },
  { nome: 'ENTACAPONA' },
  { nome: 'MALEATO DE ASENAPINA' },
  { nome: 'HEMIFUMARATO DE QUETIAPINA' },
  { nome: 'CLORIDRATO DE TIORIDAZINA' },
  { nome: 'DECANOATO DE HALOPERIDOL' },
  { nome: 'CLORPROMAZINA' },
  { nome: 'LEVOMEPROMAZINA' },
  { nome: 'HALOPERIDOL' },
  { nome: 'ZIPRASIDONA' },
  { nome: 'ZUCLOPENTIXOL' },
  { nome: 'OLANZAPINA' },
  { nome: 'QUETIAPINA' },
  { nome: 'BROMAZEPAM' },
  { nome: 'SULPIRIDA' },
  { nome: 'LEVOSSULPIRIDA' },
  { nome: 'CARBONATO DE LITIO' },
  { nome: 'RISPERIDONA' },
  { nome: 'ARIPIPRAZOL' },
  { nome: 'PALIPERIDONA' },
  { nome: 'HEMITARTARATO DE ZOLPIDEM' },
  { nome: 'CLORDIAZEPOXIDO' },
  { nome: 'LORAZEPAM' },
  { nome: 'ALPRAZOLAM' },
  { nome: 'CLOXAZOLAM' },
  { nome: 'HIDROXIZINA' },
  { nome: 'BUSPIRONA' },
  { nome: 'NITRAZEPAM' },
  { nome: 'MIDAZOLAM' },
  { nome: 'ZOPICLONA' },
  { nome: 'ZOLPIDEM' },
  { nome: 'CLORIDRATO DE FLUOXETINA' },
  { nome: 'OXALATO DE ESCITALOPRAM' },
  { nome: 'CLORIDRATO DE SERTRALINA' },
  { nome: 'CLORIDRATO DE PAROXETINA' },
  { nome: 'BROMIDRATO DE CITALOPRAM' },
  { nome: 'SUCCINATO DE DESVENLAFAXINA MONOIDRATADO' },
  { nome: 'CLORIDRATO DE VENLAFAXINA' },
  { nome: 'BROMIDRATO DE VORTIOXETINA' },
  { nome: 'CLORIDRATO DE IMIPRAMINA' },
  { nome: 'CLORIDRATO DE TRAZODONA' },
  { nome: 'CLORIDRATO DE AMITRIPTILINA' },
  { nome: 'CLORIDRATO DE CLOMIPRAMINA' },
  { nome: 'IMIPRAMINA' },
  { nome: 'CLOMIPRAMINA' },
  { nome: 'AMITRIPTILINA' },
  { nome: 'NORTRIPTILINA' },
  { nome: 'FLUOXETINA' },
  { nome: 'CITALOPRAM' },
  { nome: 'PAROXETINA' },
  { nome: 'SERTRALINA' },
  { nome: 'ESCITALOPRAM' },
  { nome: 'MOCLOBEMIDA' },
  { nome: 'MIANSERINA' },
  { nome: 'MIRTAZAPINA' },
  { nome: 'BUPROPIONA' },
  { nome: 'CLORIDRATO DE BUPROPIONA' },
  { nome: 'VENLAFAXINA' },
  { nome: 'DULOXETINA' },
  { nome: 'CLORIDRATO DE METILFENIDATO' },
  { nome: 'METILFENIDATO' },
  { nome: 'MODAFINILA' },
  { nome: 'ATOMOXETINA' },
  { nome: 'PIRACETAM' },
  { nome: 'CITICOLINA' },
  { nome: 'DONEPEZILA' },
  { nome: 'RIVASTIGMINA' },
  { nome: 'GALANTAMINA' },
  { nome: 'BROMIDRATO DE GALANTAMINA' },
  { nome: 'MEMANTINA' },
  { nome: 'GINKGO BILOBA' },
  { nome: 'CLORIDRATO DE FINGOLIMODE' },
  { nome: 'BETAPEGINTERFERONA 1A' },
  { nome: 'BETAINTERFERONA 1A' },
  { nome: 'TETRAIDROCANABINOL' },
  { nome: 'CANABIDIOL' },
  { nome: 'BETAINTERFERONA 1B' },
  { nome: 'NEOSTIGMINA' },
  { nome: 'BETANECOL' },
  { nome: 'NICOTINA' },
  { nome: 'DISSULFIRAM' },
  { nome: 'NALTREXONA' },
  { nome: 'DICLORIDRATO DE BETAISTINA' },
  { nome: 'BETAISTINA' },
  { nome: 'CINARIZINA' },
  { nome: 'FLUNARIZINA' },
  { nome: 'HEMITARTARATO DE RIVASTIGMINA' },
  { nome: 'CLORIDRATO DE DONEPEZILA' },
  { nome: 'CLORIDRATO DE MEMANTINA' },
  { nome: 'PIDOLATO DE PIRIDOXINA' },
  { nome: 'CLORIDRATO DE NALOXONA' },
  { nome: 'METILSULFATO DE NEOSTIGMINA' },
  { nome: 'TRIFOSFATO DISSODICO DE URIDINA' },
  { nome: 'FOSFATO DISSODICO DE CITIDINA' },
  { nome: 'ACETATO DE HIDROXOCOBALAMINA' },
  { nome: 'URIDINA' },
  { nome: 'CITIDINA' },
  { nome: 'NUSINERSENA' },
  { nome: 'GANGLIOSIDEOS' },
  { nome: 'RILUZOL' },
  { nome: 'AGUA DESTILADA' },
  { nome: 'CARMELOSE' },
  { nome: 'ALCATRAO DE HULHA' },
  { nome: 'ALCATRAO' },
  { nome: 'OLEO DE CADE' },
  { nome: 'LEVEDURA DE CERVEJA' },
  { nome: 'HIDROXIETILCELULOSE' },
  { nome: 'PERTUZUMABE' },
  { nome: 'SECNIDAZOL' },
  { nome: 'ETOFAMIDA' },
  { nome: 'NITAZOXANIDA' },
  { nome: 'CLORIDRATO DE LEVAMISOL' },
  { nome: 'CLOROQUINA' },
  { nome: 'HIDROXICLOROQUINA' },
  { nome: 'MEFLOQUINA' },
  { nome: 'BENZNIDAZOL' },
  { nome: 'PENTAMIDINA' },
  { nome: 'DIFOSFATO DE CLOROQUINA' },
  { nome: 'CLORIDRATO DE MEFLOQUINA' },
  { nome: 'PRAZIQUANTEL' },
  { nome: 'OXAMNIQUINA' },
  { nome: 'MEBENDAZOL' },
  { nome: 'ALBENDAZOL' },
  { nome: 'PIRANTEL' },
  { nome: 'IVERMECTINA' },
  { nome: 'PIRVINIO' },
  { nome: 'NICLOSAMIDA' },
  { nome: 'MONOSSULFIRAM' },
  { nome: 'SULFIRAM' },
  { nome: 'PERMETRINA' },
  { nome: 'BIOALETRINA' },
  { nome: 'PIPERONILA' },
  { nome: 'DELTAMETRINA' },
  { nome: 'DIPROPIONATO DE BECLOMETASONA' },
  { nome: 'TERPINA MONOIDRATADA' },
  { nome: 'CLORIDRATO DE AZELASTINA' },
  { nome: 'CLORIDRATO DE OXIMETAZOLINA' },
  { nome: 'CLORIDRATO DE NAFAZOLINA' },
  { nome: 'PROPIONATO DE FLUTICASONA' },
  { nome: 'OXIMETAZOLINA' },
  { nome: 'NAFAZOLINA' },
  { nome: 'FENOXAZOLINA' },
  { nome: 'PANTOTENOL' },
  { nome: 'CROMOGLICATO' },
  { nome: 'AZELASTINA' },
  { nome: 'BECLOMETASONA' },
  { nome: 'EFEDRINA' },
  { nome: 'SULFATO DE PSEUDOEFEDRINA' },
  { nome: 'LORATADINA' },
  { nome: 'MALEATO DE BRONFENIRAMINA' },
  { nome: 'CLORIDRATO DE FENILEFRINA' },
  { nome: 'DESLORATADINA' },
  { nome: 'CLORIDRATO DE TRIPROLIDINA' },
  { nome: 'CLORIDRATO DE PSEUDOEFEDRINA' },
  { nome: 'EPINASTINA' },
  { nome: 'SULFOGUAICOL' },
  { nome: 'TRIPROLIDINA' },
  { nome: 'CLORETO DE CETILPIRIDINIO' },
  { nome: 'CLORIDRATO DE LIDOCAINA' },
  { nome: 'QUINOSOL' },
  { nome: 'CETALCONIO' },
  { nome: 'DEXTROMETORFANO' },
  { nome: 'SULFACRISOIDINA' },
  { nome: 'DOXILAMINA' },
  { nome: 'DEQUALINIO' },
  { nome: 'SULFATO DE SALBUTAMOL' },
  { nome: 'MALEATO DE INDACATEROL' },
  { nome: 'SALBUTAMOL' },
  { nome: 'FENOTEROL' },
  { nome: 'FORMOTEROL' },
  { nome: 'OLODATEROL' },
  { nome: 'IPRATROPIO' },
  { nome: 'FLUTICASONA' },
  { nome: 'SALMETEROL' },
  { nome: 'UMECLIDINIO' },
  { nome: 'FUMARATO DE CETOTIFENO' },
  { nome: 'ACEBROFILINA' },
  { nome: 'TERBUTALINA' },
  { nome: 'TEOFILINA' },
  { nome: 'AMINOFILINA' },
  { nome: 'ZAFIRLUCAST' },
  { nome: 'MONTELUCASTE SODICO' },
  { nome: 'MONTELUCASTE' },
  { nome: 'OMALIZUMABE' },
  { nome: 'FUMARATO DE FORMOTEROL' },
  { nome: 'TRIFENATATO DE VILANTEROL' },
  { nome: 'FUROATO DE FLUTICASONA' },
  { nome: 'FUMARATO DE FORMOTEROL DI-HIDRATADO' },
  { nome: 'MONTELUCASTE DE SODIO' },
  { nome: 'BROMETO DE GLICOPIRRONIO' },
  { nome: 'BROMETO DE UMECLIDINIO' },
  { nome: 'SULFATO DE EFEDRINA' },
  { nome: 'OLEO DE EUCALIPTO' },
  { nome: 'MALEATO DE CLORFENIRAMINA' },
  { nome: 'MALEATO DE CARBINOXAMINA' },
  { nome: 'CLORIDRATO DE DIFENIDRAMINA' },
  { nome: 'CLORIDRATO DE AMBROXOL' },
  { nome: 'LOBELIA INFLATA' },
  { nome: 'BENZOATO DE SODIO' },
  { nome: 'CLORETO DE AMONIO' },
  { nome: 'EACA' },
  { nome: 'TERPINA' },
  { nome: 'GOMENOL' },
  { nome: 'BROMEXINA' },
  { nome: 'SULFOGUAIACOL' },
  { nome: 'TUAMINOEPTANO' },
  { nome: 'CARBOCISTEINA' },
  { nome: 'AMBROXOL' },
  { nome: 'SOBREROL' },
  { nome: 'FENDIZOATO DE CLOPERASTINA' },
  { nome: 'DROPROPIZINA' },
  { nome: 'CLOPERASTINA' },
  { nome: 'LEVODROPROPIZINA' },
  { nome: 'DICLORIDRATO DE CETIRIZINA' },
  { nome: 'DICLORIDRATO DE HIDROXIZINA' },
  { nome: 'CLORIDRATO DE HIDROXIZINA' },
  { nome: 'CLORIDRATO DE FEXOFENADINA' },
  { nome: 'DICLORIDRATO DE LEVOCETIRIZINA' },
  { nome: 'AMONIO' },
  { nome: 'DIFENILDRAMINA' },
  { nome: 'BUCLIZINA' },
  { nome: 'CETIRIZINA' },
  { nome: 'NIACINA' },
  { nome: 'FEXOFENADINA' },
  { nome: 'CETOTIFENO' },
  { nome: 'PIMETIXENO' },
  { nome: '2576' },
  { nome: 'ALFAPORACTANTO' },
  { nome: 'PROTEINAS' },
  { nome: 'FOSFOLIPIDIOS' },
  { nome: 'OFLOXACINO' },
  { nome: 'ACETATO DE FLUORMETOLONA' },
  { nome: 'FLUORMETOLONA' },
  { nome: 'TROMETAMOL CETOROLACO' },
  { nome: 'CETOROLACO' },
  { nome: 'NEPAFENACO' },
  { nome: 'SULFATO DE POLIMIXINA B' },
  { nome: 'TOBRAMICINA' },
  { nome: 'CLORIDRATO DE CIPROFLOXACINO MONOIDRATADO' },
  { nome: 'MALEATO DE TIMOLOL' },
  { nome: 'DEXTROTARTARATO DE BRIMONIDINA' },
  { nome: 'TAFLUPROSTA' },
  { nome: 'CLORIDRATO DE DORZOLAMIDA' },
  { nome: 'BRIMONIDINA' },
  { nome: 'ACETAZOLAMIDA' },
  { nome: 'DORZOLAMIDA' },
  { nome: 'METIPRANOLOL' },
  { nome: 'LATANOPROSTA' },
  { nome: 'TRAVOPROSTA' },
  { nome: 'BIMATOPROSTA' },
  { nome: 'CICLOPENTOLATO' },
  { nome: 'TROPICAMIDA' },
  { nome: 'MALEATO DE FENIRAMINA' },
  { nome: 'ALCOOL POLIVINILICO' },
  { nome: 'NITROFURAZONA' },
  { nome: 'ACIDO ISOSPAGLUMICO' },
  { nome: 'EMEDASTINA' },
  { nome: 'OLOPATADINA' },
  { nome: 'PROXIMETACAINA' },
  { nome: 'FLUORESCEINA' },
  { nome: 'HIPROMELOSE' },
  { nome: 'DEXTRANA' },
  { nome: 'PEGAPTANIBE' },
  { nome: 'RANIBIZUMABE' },
  { nome: 'CITRATO DE SODIO DI-HIDRATADO' },
  { nome: 'ERITRITOL' },
  { nome: 'HIALUNORATO' },
  { nome: 'BERBERINA' },
  { nome: 'SULFONATO DE ZINCO' },
  { nome: 'BORATO DE SODIO' },
  { nome: 'PEROXIDO DE UREIA' },
  { nome: 'PEROXIDO DE CARBAMIDA' },
  { nome: 'CLORFENESINA' },
  { nome: 'HEXAFLUORETO DE ENXOFRE' },
  { nome: 'AZUL DE METILENO' },
  { nome: 'PRALIDOXIMA' },
  { nome: 'DIMERCAPROL' },
  { nome: 'PROTAMINA' },
  { nome: 'FLUMAZENIL' },
  { nome: 'DEFERASIROX' },
  { nome: 'SEVELAMER' },
  { nome: 'MESNA' },
  { nome: 'FOLINATO DE CALCIO' },
  { nome: 'ACIDO FOLINICO' },
  { nome: 'AMIFOSTINA' },
  { nome: 'CLORIDRATO DE SEVELAMER' },
  { nome: 'DIATRIZOATO DE MEGLUMINA' },
  { nome: 'DIATRIZOATO DE SODIO' },
  { nome: 'IOEXOL' },
  { nome: 'IOPAMIDON' },
  { nome: 'IOPAMIDOL' },
  { nome: 'IOPROMIDA' },
  { nome: 'IODIXANOL' },
  { nome: 'SULFATO DE BARIO' },
  { nome: 'EXAMETAZIMA' },
  { nome: 'TETRAFLUORBORATO DE COBRE' },
  { nome: 'TETROFOSMINA' },
  { nome: 'CLORETO DE RADIO (223 RA)' },
  { nome: 'BRENTUXIMAB VEDOTINA' },
  { nome: 'SUMATRIPTANA' },
  { nome: 'AGOMELATINA' },
  { nome: 'IOXITALAMATO DE MEGLUMINA' },
  { nome: 'CLORIDRATO DE TIZANIDINA' },
  { nome: 'REMIFENTANILA' },
  { nome: 'SIMEPREVIR' },
  { nome: 'SILTUXIMABE' },
  { nome: 'ABIRATERONA' },
  { nome: 'DEFERIPRONA' },
  { nome: 'ETILEFRINA' },
  { nome: 'CILAZAPRIL' },
  { nome: 'METILTIONINIO' },
  { nome: 'DIBASICO' },
  { nome: 'FATOR DE COAGULACAO II, VII, IX E X' },
  { nome: 'ACIDO POLIACRILICO' },
  { nome: 'CARBOMER' },
  { nome: 'DIFLUCORTOLONA' },
  { nome: 'SULFATO DE VINCRISTINA' },
  { nome: 'CAMBENDAZOL' },
  { nome: 'NALOXONA' },
  { nome: 'CITRATO' },
  { nome: 'SODIO' },
  { nome: 'CILOSTAZOL' },
  { nome: 'ASENAPINA' },
  { nome: 'ALCAFTADINA' },
  { nome: 'METILERGOMETRINA' },
  { nome: 'CLORIDRATO DE DOXORRUBICINA' },
  { nome: 'LERCANIDIPINO' },
  { nome: 'ICATIBANTO' },
  { nome: 'ACIDO GAMAAMINOBUTIRICO' },
  { nome: 'DESFERROXAMINA' },
  { nome: 'HALOTANO' },
  { nome: 'MICAFUNGINA' },
  { nome: 'FINGOLIMODE' },
  { nome: 'CLORIDRATO DE AMIODARONA' },
  { nome: 'FENTANIL' },
  { nome: 'SIROLIMO' },
  { nome: 'TOXINA BOTULINICA TIPO A' },
  { nome: 'BAMIFILINA' },
  { nome: 'RALOXIFENO' },
  { nome: 'DIETILAMINA' },
  { nome: 'ESCINA' },
  { nome: 'FENIRAMINA' },
  { nome: 'CLOZAPINA' },
  { nome: 'RUXOLITINIB' },
  { nome: 'PERICIAZINA' },
  { nome: 'CISATRACURIO' },
  { nome: 'ACITRETINA' },
  { nome: 'LEVETIRACETAM' },
  { nome: 'LECITINA DE OVO' },
  { nome: 'RABEPRAZOLA' },
  { nome: 'LIPIDEOS' },
  { nome: 'GENCITABINA' },
  { nome: 'ALISQUIRENO' },
  { nome: 'NATALIZUMAB' },
  { nome: 'INDACATEROL' },
  { nome: 'LODENAFILA' },
  { nome: 'GEFITINIBE' },
  { nome: 'SOMATOSTATINA' },
  { nome: 'QUINISOL' },
  { nome: 'SUXAMETONIO' },
  { nome: 'CARBONATO DE BISMUTO' },
  { nome: 'PRASUGREL' },
  { nome: 'FLURAZEPAM' },
  { nome: 'NANDROLONA' },
  { nome: 'ALFENTANILA' },
  { nome: 'IOMEPROL' },
  { nome: 'SUGAMADEX' },
  { nome: 'LAPATINIBE' },
  { nome: 'CLORIDRATO DE TERBINAFINA' },
  { nome: 'TENSIROLIMO' },
  { nome: 'GLICOPIRRONIO' },
  { nome: 'CALCITRIOL' },
  { nome: 'COMPLEXO PROTROMBINICO PARCIAL, HUMANO (FATORES II, IX E X)' },
  { nome: 'METILPREDNISOLONA, SUCCINATO' },
  { nome: 'IDARRUBICINA' },
  { nome: 'PITAVASTATINA' },
  { nome: 'FEMPROCUMONA' },
  { nome: 'CERTOLIZUMAB' },
  { nome: 'VACINA VIRUS INFLUENZA, VIVO, TRIVALENTE' },
  { nome: 'LORNOXICAM' },
  { nome: 'RASBURICASE' },
  { nome: 'CINACALCET' },
  { nome: 'MIRABEGRONA' },
  { nome: 'ALFACORIFOLITROPINA' },
  { nome: 'NICERGOLINA' },
  { nome: 'INTERFERONA BETA 1A' },
  { nome: 'LENVATINIBE' },
  { nome: 'ABACAVIR' },
  { nome: 'FRACAO FOSFOLIPIDICA DE PULMAO DE PORCO' },
  { nome: 'LEVOCETIRIZINA' },
  { nome: 'SEVOFLURANO' },
  { nome: 'BILASTINA' },
  { nome: 'VILDAGLIPTINA' },
  { nome: 'NIMOTUZUMABE' },
  { nome: 'ISOTIPENDIL' },
  { nome: 'LISADO BACTERIANO DE ESCHERICHIA COLI' },
  { nome: 'ROMIPLOSTIM' },
  { nome: 'PICOSSULFATO SODICO' },
  { nome: 'DALTEPARINA' },
  { nome: 'VIGABATRINA' },
  { nome: 'REBOXETINA' },
  { nome: 'TIANEPTINA' },
  { nome: 'ETORICOXIBE' },
  { nome: 'TAFAMIDIS MEGLUMINA' },
  { nome: 'GANIRELIX' },
  { nome: 'LIPEGFILGRASTIM' },
  { nome: 'HALOBETASOL' },
  { nome: 'ALFATOCOFEROL' },
  { nome: 'BETAFOLITROPINA' },
  { nome: 'TETRIZOLINA' },
  { nome: 'ALIROCUMAB' },
  { nome: 'TOFACITINIBE' },
  { nome: 'POLIXINA B' },
  { nome: 'VERTEPORFINA' },
  { nome: 'TEGASERODE' },
  { nome: 'SULFOGUAIACOLATO DE POTASSIO' },
  { nome: 'AZUL PATENTE V' },
  { nome: 'OLEO DE PAPOULA IODADO' },
  { nome: 'LIDOCIANA' },
  { nome: 'ACETATO DE DEXAMETASONA' },
  { nome: 'HEXAMIDINA' },
  { nome: 'OXICODONA' },
  { nome: 'ALFANONACOGUE' },
  { nome: 'ACIDO AMINOCAPROICO' },
  { nome: 'IMUNOGLOBULINA HEPATITE B' },
  { nome: 'AMBRISENTANA' },
  { nome: 'FONDAPARINUX SODICO' },
  { nome: 'OSELTAMIVIR' },
  { nome: 'VORTIOXETINA' },
  { nome: 'CLORIDRATO DE TOPOTECANA' },
  { nome: 'CANAQUINUMAB' },
  { nome: 'GLUTAMINA' },
  { nome: 'PENCICLOVIR' },
  { nome: 'TRAZODONA' },
  { nome: 'ALFA-1-ANTITRIPSINA' },
  { nome: 'INSULINA ASPART' },
  { nome: 'DARBEPOETINA ALFA' },
  { nome: 'BELIMUMAB' },
  { nome: 'DESLANOSIDEO' },
  { nome: 'DESVENLAFAXINA' },
  { nome: 'FILGRASTIMA' },
  { nome: 'CISTEINA' },
  { nome: 'BISMUTO COLOIDAL' },
  { nome: 'SAPROPTERINA' },
  { nome: 'TRAMETINIB' },
  { nome: 'SULFATO ZINCO' },
  { nome: 'FUMARATO DE DIMETILA' },
  { nome: 'GOLIMUMAB' },
  { nome: 'MARAVIROQUE' },
  { nome: 'CARFILZOMIBE' },
  { nome: 'UDENAFILA' },
  { nome: 'PIRIDOSTIGMINA' },
  { nome: 'FOSFOSERINA' },
  { nome: 'FOSFOTREONINA' },
  { nome: 'HIDROXICOBALAMINA' },
  { nome: 'EXEMESTANO' },
  { nome: 'TIZANIDINA' },
  { nome: 'DABRAFENIBE' },
  { nome: 'PEGVISOMANTO' },
  { nome: 'ERIBULINA' },
  { nome: 'GADODIAMIDA' },
  { nome: 'OXIFEMBUTASONA' },
  { nome: 'FERRRO AMINOACIDO QUELATO' },
  { nome: 'PALIVIZUMABE' },
  { nome: 'BASILIXIMABE' },
  { nome: 'FLUNITRAZEPAM' },
  { nome: 'UFTEQUINUMABE' },
  { nome: 'USTEQUINUMAB' },
  { nome: 'LEVOTIROXINA SODICA' },
  { nome: 'XILOMETAZOLINA' },
  { nome: 'CLOBAZAM' },
  { nome: 'ALFUZOSINA' },
  { nome: 'ANAGRELIDA' },
  { nome: 'AXITINIBE' },
  { nome: 'BUMETANIDA' },
  { nome: 'SOFOSBUVIR' },
  { nome: 'CICLESONIDA' },
  { nome: 'CANAGLIFLOZINA' },
  { nome: 'ACIDO GADOTERICO' },
  { nome: 'VINFLUNINA' },
  { nome: 'CRIZOTINIBE' },
  { nome: 'IVABRADINA' },
  { nome: 'BIFONAZOL' },
  { nome: 'AMINAFTONA' },
  { nome: 'PAZOPANIBE' },
  { nome: 'NINTEDANIBE' },
  { nome: 'RASAGILINA' },
  { nome: 'FOTEMUSTINA' },
  { nome: 'VEMURAFENIB' },
  { nome: 'LEVAMISOL' },
  { nome: 'POLIESTIRENOSSULFONATO DE CALCIO' },
  { nome: 'RALTEGRAVIR' },
  { nome: 'PINDOLOL' },
  { nome: 'VALGANCICLOVIR' },
  { nome: 'ADALIMUMABE' },
  { nome: 'DINOPROSTONA' },
  { nome: 'DEGARELIX' },
  { nome: 'ROFLUMILAST' },
  { nome: 'OLEATO DE MONOETANOLAMINA' },
  { nome: 'IMIGLUCERASE' },
  { nome: 'IBRUTINIBE' },
  { nome: 'CLOBUTINOL' },
  { nome: 'FLUFENAZINA' },
  { nome: 'REGORAFENIBE' },
  { nome: 'INTERFERONA BETA 1 B' },
  { nome: 'LOXOPROFENO DE SODIO' },
  { nome: 'NITRATO DE ISOCONAZOL' },
  { nome: 'SOLIFENACINA' },
  { nome: 'ATAZANAVIR' },
  { nome: 'ABATACEPTE' },
  { nome: 'CLORIDRATO DE DOPAMINA' },
  { nome: 'CETRORELIX' },
  { nome: 'CUMARINA' },
  { nome: 'TROXERRUTINA' },
  { nome: 'FLUTRIMAZOL' },
  { nome: 'LIRAGLUTIDA' },
  { nome: 'ZINAMIVIR' },
  { nome: 'NATEGLINIDA' },
  { nome: 'CLADRIBINA' },
  { nome: 'DESFLURANO' },
  { nome: 'ABCIXIMAB' },
  { nome: 'ACETATO DE PREDNISOLONA' },
  { nome: 'LIXISENATIDO' },
  { nome: 'GADOBUTROL' },
  { nome: 'NORELGESTROMINA' },
  { nome: 'BUTACONAZOL' },
  { nome: 'RUPATADINA' },
  { nome: 'CLORIDRATO DE NALBUFINA' },
  { nome: 'NALBUFINA' },
  { nome: 'TIOTROPIO' },
  { nome: 'TROLAMINA' },
  { nome: 'LANREOTIDA' },
  { nome: 'ERLONITIBE' },
  { nome: 'SORAFENIBE' },
  { nome: 'VANDETANIB' },
  { nome: 'ACARBOSE' },
  { nome: 'TERLIPRESSINA' },
  { nome: 'CLORIDRATO DE IRINOTECANO TRIIDRATADO' },
  { nome: 'EPIMASTINA' },
  { nome: 'ROTIGOTINA' },
  { nome: 'ALFAVELAGLICERASE' },
  { nome: 'POSACONAZOL' },
  { nome: 'LAURILSULFATO DE SODIO' },
  { nome: 'BENZOXIQUINA' },
  { nome: 'AMANTADINA' },
  { nome: 'RIVAROXABANA' },
  { nome: 'MECLIZINA' },
  { nome: 'DESOXIMETASONA' },
  { nome: 'ISETIONATO DE HEXAMIDINA' },
  { nome: 'CLORIDRATO DE TETRACAINA' },
  { nome: 'GADOTERIDOL' },
  { nome: 'PROPILTIOURACILA' },
  { nome: 'LEVOBUNOLOL' },
  { nome: 'MILRINONA' },
  { nome: 'ALIZAPRIDA' },
  { nome: 'TICAGRELOR' },
  { nome: 'GLATIRAMER' },
  { nome: 'PROGESTERONA' },
  { nome: 'ACIDO DESIDROCOLICO' },
  { nome: 'DORNASE ALFA' },
  { nome: 'DIAZOXIDO' },
  { nome: 'FLUVOXAMINA' },
  { nome: 'RANELATO DE ESTRONCIO' },
  { nome: 'IOXAGLATO DE MEGLUMINA' },
  { nome: 'IOXAGLATO DE SODIO' },
  { nome: 'METIONINIO' },
  { nome: 'TEOBROMINA' },
  { nome: 'MITOTANO' },
  { nome: 'VEDOLIZUMAB' },
  { nome: 'RIOCIGUATE' },
  { nome: 'CONCENTRADO DE COMPLEXO PROTROMBINICO' },
  { nome: 'CETUXIMABE' },
  { nome: 'DIPIRIDAMOL' },
  { nome: 'CABERGOLINA' },
  { nome: 'INSULINA DEGLUDECA' },
  { nome: 'DEFEROXAMINA' },
  { nome: 'SULFATO DE COBRE' },
  { nome: 'MEBEVERINA' },
  { nome: 'PENICILAMINA' },
  { nome: 'PEGINTERFERON ALFA-2A' },
  { nome: 'RITUXIMABE' },
  { nome: 'LEVOSIMENDANA' },
  { nome: 'SOLIFENACIN' },
  { nome: 'ALFALUTROPINA' },
  { nome: 'LUTROPINA ALFA' },
  { nome: 'TERIFLUNOMIDA' },
  { nome: 'MAGALDRATO' },
  { nome: 'BERACTANT' },
  { nome: 'LISDEXANFETAMINA' },
  { nome: 'CLORIDRATO DE NEBIVOLOL' },
  { nome: 'BAMBUTEROL' },
  { nome: 'OXICONAZOL' },
  { nome: 'DEXRAZOXANO' },
  { nome: 'MANIDIPINO' },
  { nome: 'PIRFENIDONA' },
  { nome: 'CLONIDINA' },
  { nome: 'PIMOZIDA' },
  { nome: 'CATUABA' },
  { nome: 'MARAPUAMA' },
  { nome: 'MULTIVITAMINAS' },
  { nome: 'CITRATO DE CALCIO' },
  { nome: 'IDURSULFASE' },
  { nome: 'TIAMAZOL' },
  { nome: 'VALACICLOVIR' },
  { nome: 'ADEFOBIR DIPIVOXIL' },
  { nome: 'CLORIDRATO DE PROPRANOLOL' },
  { nome: 'VALDECOXIBE' },
  { nome: 'PARECOXIBE' },
  { nome: 'FURAZOLIDONA' },
  { nome: 'ESTAZOLAM' },
  { nome: 'PIRIBEDIL' },
  { nome: 'QUINOFORMIO' },
  { nome: 'ALMITRINA' },
  { nome: 'LOTEPREDNOL' },
  { nome: 'DIMETINDENO' },
  { nome: 'OSIMERTINIBE' },
  { nome: 'INSULINA DETERMIR' },
  { nome: 'EBASTINA' },
  { nome: 'TIPRANAVIR' },
  { nome: 'COBIMETINIBE' },
  { nome: 'PIDOLATO DE MAGNESIO' },
  { nome: 'BROMOCRIPTINA' },
  { nome: 'VISMODEGIB' },
  { nome: 'SULFATO DE ALUMINIO' },
  { nome: 'LACIDIPINO' },
  { nome: 'CARBOXIMETILCELULOSE' },
  { nome: 'PILOCARPINA' },
  { nome: 'BEMIPARINA' },
  { nome: 'BUSSERRELINA' },
  { nome: 'CARBACOL' },
  { nome: 'BENAZEPRIL' },
  { nome: 'MAPROTILINA' },
  { nome: 'DASATINIBE' },
  { nome: 'ALFAGALSIDASE' },
  { nome: 'SAIS MINERAIS PARA HIDRATACAO' },
  { nome: 'DOXORRUBICINA LIPOSSOMAL' },
  { nome: 'BOCEPREVIR' },
  { nome: 'TELAPREVIR' },
  { nome: 'OBINUTUZUMAB' },
  { nome: 'METADONA' },
  { nome: 'DANAZOL' },
  { nome: 'PIZOTIFENO' },
  { nome: 'TRANILCIPROMINA' },
  { nome: 'TRIOXIDO ARSENIO' },
  { nome: 'MUCOPOLISSACARIDASE' },
  { nome: 'GADOPENTETATO DE DIMEGLUMINA' },
  { nome: 'IDOXURIDINA' },
  { nome: 'CALCIPOTRIOL' },
  { nome: 'INGENOL' },
  { nome: 'N(2)-L-ALANIL-L-GLUTAMINA' },
  { nome: 'SOTALOL' },
  { nome: 'ENFUVIRTIDA' },
  { nome: 'CLOPAMIDA' },
  { nome: 'CLEMASTINA' },
  { nome: 'BETAGALSIDASE' },
  { nome: 'PLERIXAFOR' },
  { nome: 'GADOXETATO' },
  { nome: 'ESMOLOL' },
  { nome: 'VIMINOL' },
  { nome: 'AMINOACIDO QUELATO DE FERRO' },
  { nome: 'ALENDRONATO' },
  { nome: 'ALFATIROTROFINA' },
  { nome: 'GOSSERRELINA' },
  { nome: 'SUCRALFATO' },
  { nome: 'ANTIMONIATO DE MEGLUMINA' },
  { nome: 'SOLUCAO DE COALTAR' },
  { nome: 'ACRIFLAVINA' },
  { nome: 'FOSFATO DE CALCIO' },
  { nome: 'PIPOTIAZINA' },
  { nome: 'TRIMEBUTINA' },
  { nome: 'TECLOZANA' },
  { nome: 'INDOMETACINA' },
  { nome: 'MIGLUSTATE' },
  { nome: 'MESTEROLONA' },
  { nome: 'DANTROLENO' },
  { nome: 'OXIBUPROCAINA' },
  { nome: 'ALFAESTRADIOL' },
  { nome: 'LACTATO DE AMONIO' },
  { nome: 'SULFATO DE TERBUTALINA' },
  { nome: 'OXIMETOLONA' },
  { nome: 'RIZATRIPTANA' },
  { nome: 'CEPALINA' },
  { nome: 'MONOSSIALOGANGLIOSIDEO' },
  { nome: 'AFATINIBE' },
  { nome: 'FOSFATO DE BETAMETASONA' },
  { nome: 'SUNITINIBE' },
  { nome: 'COLESTIRAMINA' },
  { nome: 'ALFAGLICOSIDASE' },
  { nome: 'BUTENAFINA' },
  { nome: 'ACIDO TIOCTICO' },
  { nome: 'FATOR DE COAGULACAO VIII E DE VON WILLEBRAND' },
  { nome: 'SECUQUINUMABE' },
  { nome: 'FLUOCORTOLONA' },
  { nome: 'PIRENOXINA' },
  { nome: 'POLICARBOFILA CALCICA' },
  { nome: 'POLICARBOFILA' },
  { nome: 'HIDRALAZINA' },
  { nome: 'CONCENTRADO DE FATOR DE VII' },
  { nome: 'ACIDO ALENDRONICO' },
  { nome: 'IOBITRIDOL' },
  { nome: 'ENTECAVIR' },
  { nome: 'VARENICLINA' },
  { nome: 'IPILIMUMAB' },
  { nome: 'DULAGLUTIDA' },
  { nome: 'TIROFIBANA' },
  { nome: 'FUSAFUNGINA' },
  { nome: 'PIMECROLIMO' },
  { nome: 'GADOVERSETAMIDA' },
  { nome: 'IOVERSOL' },
  { nome: 'OXETACAINA' },
  { nome: 'VIMPOCETINA' },
  { nome: 'VASOPRESSINA' },
  { nome: 'ARGIPRESSINA' },
  { nome: 'LOMUSTINA' },
  { nome: 'BEVACIZUMABE' },
  { nome: 'VITELINATO DE PRATA' },
  { nome: 'OCRIPLASMINA' },
  { nome: 'PIRIMETAMINA' },
  { nome: 'TRIFLUOPERAZINA' },
  { nome: 'POLISSORBATO' },
  { nome: 'ACIDO URSODESOXICOLICO' },
  { nome: 'ERGOMETRINA' },
  { nome: 'BENFOTIAMINA' },
  { nome: 'BUFLOMEDIL' },
  { nome: 'FAMPRIDINA' },
  { nome: 'RILMENIDINA' },
  { nome: 'GLUCONATO DE CALCIO' },
  { nome: 'TIORIDAZINA' },
  { nome: 'INTERLEUCINA-2' },
  { nome: 'METARAMINOL' },
  { nome: 'VARFARINA SODICA' },
  { nome: 'ACETATO DE SODIO' },
  { nome: 'ACIDO MALICO' },
  { nome: 'TOLCAPONE' },
  { nome: 'CLORZOXAZONA' },
  { nome: 'SUBACETATO DE ALUMINIO' },
  { nome: 'POLIMIXINA B' },
  { nome: 'OTILONIO' },
  { nome: 'TRIEXIFENIDIL' },
  { nome: 'PRIMIDONA' },
  { nome: 'CARBONATO MAGNESIO' },
  { nome: 'DIETILESTILBESTROL' },
  { nome: 'ETOSSUXIMIDA' },
  { nome: 'IOTALAMATO' },
  { nome: 'ISOXSUPRINA' },
  { nome: 'ACIDO MUCOPOLISSACARIDO POLISSULFURICO' },
  { nome: 'LARONIDASE' },
  { nome: 'ELTROMBOPAG OLAMINA' },
  { nome: 'CLORQUINALDOL' },
  { nome: 'CLORIDRATO DE NORTRIPTILINA' },
  { nome: 'MISOPROSTOL' },
  { nome: 'DABIGATRANA' },
  { nome: 'DEXTROCETAMINA' },
  { nome: 'EMPAGLIFLOZINA' },
  { nome: 'FOSAMPRENAVIR' },
  { nome: 'BACILLUS CEREUS' },
  { nome: 'IOIMBINA' },
  { nome: 'AMISSULPRIDA' },
  { nome: 'ACIDO IOXITALAMICO' },
  { nome: 'AMILOCAINA' },
  { nome: 'FRAMICETINA' },
  { nome: 'AMOXICILINA' },
  { nome: 'TARTARATO DE BISMUTO DE SODIO' },
  { nome: 'DOXICICLINA' },
  { nome: 'TIOMERSAL' },
  { nome: 'NITRATO DE CERIO' },
  { nome: 'OXITETRACICLINA' },
  { nome: 'CLINDAMICINA' },
  { nome: 'ERITROMICINA' },
  { nome: 'PROPIONATO DE SODIO' },
  { nome: 'NIMORAZOL' },
  { nome: 'MINOCICLINA' },
  { nome: 'SUCCINATO SODICO DE CLORANFENICOL' },
  { nome: 'TOSILATO DE SULTAMICILINA' },
  { nome: 'CLAVULANATO DE POTASSIO' },
  { nome: 'SULBACTAM SODICA' },
  { nome: 'AMPICILINA SODICA' },
  { nome: 'TAZOBACTAM SODICO' },
  { nome: 'PIPERACILINA SODICA' },
  { nome: 'AMPICILINA' },
  { nome: 'BENZILPENICILINA POTASSICA' },
  { nome: 'BENZILPENICILINA PROCAINA' },
  { nome: 'AMPICILINA BENZATINA' },
  { nome: 'FENOXIMETILPENICILINA' },
  { nome: 'BENZILPENICILINA BENZATINA' },
  { nome: 'OXACILINA' },
  { nome: 'SULBACTAM' },
  { nome: 'PROBENECIDA' },
  { nome: 'CLAVULANATO' },
  { nome: 'TICARCILINA' },
  { nome: 'ACIDO CLAVULANICO' },
  { nome: 'PIPERACILINA' },
  { nome: 'TAZOBACTAM' },
  { nome: 'AXETILCEFUROXIMA' },
  { nome: 'CEFALEXINA MONOIDRATADA' },
  { nome: 'CEFALOTINA SODICA' },
  { nome: 'CEFOXITINA SODICA' },
  { nome: 'CEFTRIAXONA SODICA' },
  { nome: 'CLORIDRATO DE CEFEPIMA' },
  { nome: 'CEFOTAXIMA SODICA' },
  { nome: 'CEFAZOLINA SODICA' },
  { nome: 'CEFTRIAXONA DISSODICA HEMIEPTAIDRATADA' },
  { nome: 'CEFTAROLINA FOSAMILA' },
  { nome: 'CEFUROXIMA SODICA' },
  { nome: 'CEFALEXINA' },
  { nome: 'CEFALOTINA' },
  { nome: 'CEFAZOLINA' },
  { nome: 'CEFADROXILA' },
  { nome: 'CEFOXITINA' },
  { nome: 'CEFUROXIMA' },
  { nome: 'CEFACLOR' },
  { nome: 'CEFPROZILA' },
  { nome: 'CEFOTAXIMA' },
  { nome: 'CEFTAZIDIMA' },
  { nome: 'CEFTRIAXONA' },
  { nome: 'CEFEPIMA' },
  { nome: 'CEFPIROMA' },
  { nome: 'AZTREONAM' },
  { nome: 'MEROPENEM' },
  { nome: 'DORIPENEM' },
  { nome: 'CILASTATINA' },
  { nome: 'IMIPENEM' },
  { nome: 'SULFAMETOXAZOL' },
  { nome: 'TRIMETOPRIMA' },
  { nome: 'SULFADIAZINA' },
  { nome: 'ESTOLATO DE ERITROMICINA' },
  { nome: 'ROXITROMICINA' },
  { nome: 'AZITROMICINA' },
  { nome: 'TELITROMICINA' },
  { nome: 'LINCOMICINA' },
  { nome: 'CLORIDRATO DE MOXIFLOXACINO' },
  { nome: 'LEVOFLOXACINO HEMI-HIDRATADO' },
  { nome: 'LEVOFLOXACINO HEMIIDRATADO' },
  { nome: 'LEVOFLOXACINO HEMIDRATADO' },
  { nome: 'AMICACINA' },
  { nome: 'PENICILINA G BENZATINA' },
  { nome: 'OXACILINA SODICA' },
  { nome: 'SULFATO DE AMICACINA' },
  { nome: 'SULFATO DE TOBRAMICINA' },
  { nome: 'PEFLOXACINO' },
  { nome: 'NORFLOXACINO' },
  { nome: 'LOMEFLOXACINO' },
  { nome: 'LEVOFLOXACINO' },
  { nome: 'MOXIFLOXACINO' },
  { nome: 'ACIDO PIPEMIDICO' },
  { nome: 'MEROPENEM TRI-HIDRATADO' },
  { nome: 'ERTAPENEM SODICO' },
  { nome: 'IMIPENEM MONOIDRATADO' },
  { nome: 'CILASTATINA SODICA' },
  { nome: 'CLORIDRATO DE VANCOMICINA' },
  { nome: 'COLISTIMETATO DE SODIO' },
  { nome: 'DAPTOMICINA' },
  { nome: 'VANCOMICINA' },
  { nome: 'TEICOPLANINA' },
  { nome: 'COLISTIMETATO' },
  { nome: 'LINEZOLIDA' },
  { nome: 'RIFAMPICINA' },
  { nome: 'RIFABUTINA' },
  { nome: 'ISONIAZIDA' },
  { nome: 'ETAMBUTOL' },
  { nome: 'DAPSONA' },
  { nome: 'MITOMICINA' },
  { nome: 'SULFADOXINA' },
  { nome: 'ACIDO TANICO' },
  { nome: 'ALFAZEMA' },
  { nome: 'BALSAMO DE TOLU' },
  { nome: 'SULFANILAMIDA' },
  { nome: 'TITURA DE BENJOIM' },
  { nome: 'GATIFLOXACINA' },
  { nome: 'FENOXIMETILPENICILINA POTASSICA' },
  { nome: 'TIGECICLINA' },
  { nome: 'LIMECICLINA' },
  { nome: 'CLORIDRATO DE LINCOMICINA' },
  { nome: 'CLOSTEBOL' },
  { nome: 'ERTAPENEM' },
  { nome: 'GEMIFLOXACINO' },
  { nome: 'BESIFLOXACINO' },
  { nome: 'PEROXIDO DE ZINCO' },
  { nome: 'POLIMICINA B' },
  { nome: 'FOSFOMICINA' },
  { nome: 'ATAPULGITA' },
  { nome: 'TIANFENICOL' },
  { nome: 'ESPIRAMICINA' },
  { nome: 'RETAPAMULINA' },
];
