export const medicines = [
  {
    nome: 'ESTOMAZIL',
    farmaco: null,
    farmacos: ['ACIDO CITRICO', 'CARBONATO DE SODIO', 'BICARBONATO DE SODIO'],
    concentracao: '(462+90+438)',
    unidade: 'MG/G',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'PO EFERVESCENTE',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02A1',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '540916090022803',
    MIP: true,
    label: 'ESTOMAZIL (462+90+438)MG/G - PO EFERVESCENTE',
    unificado: null,
  },
  {
    nome: 'DIGIAZIA',
    farmaco: null,
    farmacos: ['ACIDO CITRICO', 'CARBONATO DE SODIO', 'BICARBONATO DE SODIO'],
    concentracao: '460 + 100 + 440',
    unidade: 'MG/G',
    tipoMedicamento: 'REFERENCIA',
    formaFarmaceutica: 'PO EFERVESCENTE',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02A1',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '526217070014604',
    MIP: true,
    label: 'DIGIAZIA 460 + 100 + 440MG/G - PO EFERVESCENTE',
    unificado: null,
  },
  {
    nome: 'FRUTAXX',
    farmaco: null,
    farmacos: ['ACIDO CITRICO', 'CARBONATO DE SODIO', 'BICARBONATO DE SODIO'],
    concentracao: '462 + 438 + 90',
    unidade: 'MG/G',
    tipoMedicamento: 'REFERENCIA',
    formaFarmaceutica: 'PO EFERVESCENTE',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02A1',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '533017040065104',
    MIP: true,
    label: 'FRUTAXX 462 + 438 + 90MG/G - PO EFERVESCENTE',
    unificado: null,
  },
  {
    nome: 'SIMETICONA;EMULSAO DE SIMETICONE 30%',
    farmaco: null,
    farmacos: ['SIMETICONA', 'EMULSAO DE SIMETICONE 30%'],
    concentracao: '75',
    unidade: 'MG/ML',
    tipoMedicamento: 'GENERICO',
    formaFarmaceutica: 'EMULSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02A2',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '510417020149606',
    MIP: true,
    label: 'SIMETICONA;EMULSAO DE SIMETICONE 30% 75MG/ML - EMULSAO ORAL',
    unificado: null,
  },
  {
    nome: 'GASTROGEL',
    farmaco: null,
    farmacos: ['HIDROXIDO DE MAGNESIO', 'HIDROXIDO DE ALUMINIO', 'DIMETICONA'],
    concentracao: '200 + 200 + 30',
    unidade: 'MG',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'COMPRIMIDO',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02A4',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '525115060025903',
    MIP: true,
    label: 'GASTROGEL 200 + 200 + 30MG - COMPRIMIDO',
    unificado: null,
  },
  {
    nome: 'GELTRAT',
    farmaco: null,
    farmacos: ['HIDROXIDO DE MAGNESIO', 'HIDROXIDO DE ALUMINIO', 'DIMETICONA'],
    concentracao: '37 + 40 + 5',
    unidade: 'MG/ML',
    tipoMedicamento: 'REFERENCIA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02A4',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '562717070000804',
    MIP: true,
    label: 'GELTRAT 37 + 40 + 5MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'GASTROGEL',
    farmaco: null,
    farmacos: ['HIDROXIDO DE MAGNESIO', 'HIDROXIDO DE ALUMINIO', 'DIMETICONA'],
    concentracao: '40 + 30 + 3',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02A4',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '525115060025803',
    MIP: true,
    label: 'GASTROGEL 40 + 30 + 3MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'LEITE DE MAGNESIA PHILLIPS',
    farmaco: null,
    farmacos: ['HIDROXIDO DE MAGNESIO'],
    concentracao: '80',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AA04',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '0000001295',
    MIP: true,
    label: 'LEITE DE MAGNESIA PHILLIPS 80MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'LEITE MAGNESIA',
    farmaco: null,
    farmacos: ['HIDROXIDO DE MAGNESIO'],
    concentracao: '80',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AA04',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '528101404133415',
    MIP: true,
    label: 'LEITE MAGNESIA 80MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'LEITE DE MAGNESIA',
    farmaco: null,
    farmacos: ['HIDROXIDO DE MAGNESIO'],
    concentracao: '80,95',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AA04',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '518702401131413',
    MIP: true,
    label: 'LEITE DE MAGNESIA 80,95MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'LEITE DE MAGNESIA DE PHILLIPS',
    farmaco: null,
    farmacos: ['HIDROXIDO DE MAGNESIO'],
    concentracao: '80,95',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AA04',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '510604802136412',
    MIP: true,
    label: 'LEITE DE MAGNESIA DE PHILLIPS 80,95MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'LEITE DE MAGNESIA DE PHILLIPS',
    farmaco: null,
    farmacos: ['HIDROXIDO DE MAGNESIO'],
    concentracao: '85,5',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AA04',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '510604804139419',
    MIP: true,
    label: 'LEITE DE MAGNESIA DE PHILLIPS 85,5MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'KOLLANGEL FF',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO', 'MAGNESIO'],
    concentracao: '',
    unidade: 'MG',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'PO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '540415080009207',
    MIP: true,
    label: 'KOLLANGEL FF MG - PO ORAL',
    unificado: null,
  },
  {
    nome: 'GELDROX',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO', 'HIDROXIDO DE MAGNESIO', 'SIMETICONA'],
    concentracao: '',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '505514010021304',
    MIP: true,
    label: 'GELDROX MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'PRODIGEST',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO', 'HIDROXIDO DE MAGNESIO', 'SIMETICONA'],
    concentracao: '',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '528531207139116',
    MIP: true,
    label: 'PRODIGEST MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'HIDROTHEO GEL',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO', 'MAGNESIO'],
    concentracao: '300 + 200',
    unidade: 'MG/5ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '241807',
    MIP: true,
    label: 'HIDROTHEO GEL 300 + 200MG/5ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'GASTRI-VYR',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO', 'MAGNESIO'],
    concentracao: '37 + 35,6',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '505505701130413',
    MIP: true,
    label: 'GASTRI-VYR 37 + 35,6MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'HIDROXIDO DE ALUMINIO + MAGNESIO',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO', 'MAGNESIO'],
    concentracao: '60 + 40',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '0000030890',
    MIP: true,
    label: 'HIDROXIDO DE ALUMINIO + MAGNESIO 60 + 40MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'KOLANTYL GEL',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO', 'MAGNESIO'],
    concentracao: '60 + 40',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '0000030837',
    MIP: true,
    label: 'KOLANTYL GEL 60 + 40MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'STONGEL',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO', 'MAGNESIO'],
    concentracao: 'ASSOCIACAO',
    unidade: '',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'COMPRIMIDO',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '0000012416',
    MIP: true,
    label: 'STONGEL ASSOCIACAO - COMPRIMIDO',
    unificado: null,
  },
  {
    nome: 'KAOMAGMA',
    farmaco: null,
    farmacos: ['CAOLIM COLOIDAL', 'HIDROXIDO DE ALUMINIO', 'PECTINA CITRICA'],
    concentracao: '1500 + 135 + 200',
    unidade: 'MG/5ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '0000003581',
    MIP: true,
    label: 'KAOMAGMA 1500 + 135 + 200MG/5ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'CAOLIM COLOIDAL + HIDROXIDO DE ALUMINIO + PECTINA CITRICA',
    farmaco: null,
    farmacos: ['CAOLIM COLOIDAL', 'HIDROXIDO DE ALUMINIO', 'PECTINA CITRICA'],
    concentracao: '1500 + 135 + 200',
    unidade: 'MG/5ML',
    tipoMedicamento: 'GENERICO',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '0000003581',
    MIP: true,
    label:
      'CAOLIM COLOIDAL + HIDROXIDO DE ALUMINIO + PECTINA CITRICA 1500 + 135 + 200MG/5ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'BIODROX',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '230',
    unidade: 'MG',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'COMPRIMIDO',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '503900501118413',
    MIP: true,
    label: 'BIODROX 230MG - COMPRIMIDO',
    unificado: null,
  },
  {
    nome: 'GASTROPEPT',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '230',
    unidade: 'MG',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'COMPRIMIDO',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '528101301113411',
    MIP: true,
    label: 'GASTROPEPT 230MG - COMPRIMIDO',
    unificado: null,
  },
  {
    nome: 'BIODROX',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '230',
    unidade: 'MG/5ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '503900503137415',
    MIP: true,
    label: 'BIODROX 230MG/5ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'DUCTOGEL',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '300',
    unidade: 'MG',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'COMPRIMIDO',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '516703302114410',
    MIP: true,
    label: 'DUCTOGEL 300MG - COMPRIMIDO',
    unificado: null,
  },
  {
    nome: 'GASTROX',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '300',
    unidade: 'MG',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'COMPRIMIDO',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '510803202112411',
    MIP: true,
    label: 'GASTROX 300MG - COMPRIMIDO',
    unificado: null,
  },
  {
    nome: 'HIDROXIDO DE ALUMINIO',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '6,2',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '513001901137410',
    MIP: true,
    label: 'HIDROXIDO DE ALUMINIO 6,2MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'DUCTOGEL',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '60',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '0000009867',
    MIP: true,
    label: 'DUCTOGEL 60MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'HIDROTHEO',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '60',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '234905',
    MIP: true,
    label: 'HIDROTHEO 60MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'HIDROXIDO DE ALUMINIO',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '60',
    unidade: 'MG/ML',
    tipoMedicamento: 'GENERICO',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '510003401137411',
    MIP: true,
    label: 'HIDROXIDO DE ALUMINIO 60MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'HIDROXIMED',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '60',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '0000033046',
    MIP: true,
    label: 'HIDROXIMED 60MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'GASTROPEPT',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '61,5',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '528101302136415',
    MIP: true,
    label: 'GASTROPEPT 61,5MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'HIDROXIDO DE ALUMINIO',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '61,5',
    unidade: 'MG/ML',
    tipoMedicamento: 'GENERICO',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '528503412130111',
    MIP: true,
    label: 'HIDROXIDO DE ALUMINIO 61,5MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'GASTRONOL',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '62',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '514602202134414',
    MIP: true,
    label: 'GASTRONOL 62MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'GASTROX',
    farmaco: null,
    farmacos: ['HIDROXIDO DE ALUMINIO'],
    concentracao: '62',
    unidade: 'MG/ML',
    tipoMedicamento: 'SIMILAR',
    formaFarmaceutica: 'SUSPENSAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AB01',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '510803204131411',
    MIP: true,
    label: 'GASTROX 62MG/ML - SUSPENSAO ORAL',
    unificado: null,
  },
  {
    nome: 'FLUORETO DE SODIO',
    farmaco: null,
    farmacos: ['FLUORETO DE SODIO'],
    concentracao: '0,5',
    unidade: 'MG/ML',
    tipoMedicamento: 'NAO CLASSIFICADO PELA ANVISA',
    formaFarmaceutica: 'SOLUCAO ORAL',
    viaAdministracao: 'ORAL',
    codigoATC: 'A02AC',
    usoInterno: true,
    antimicrobiano: false,
    bula: null,
    portaria344: '',
    controleEspecial: false,
    TISS: '519601302136418',
    MIP: true,
    label: 'FLUORETO DE SODIO 0,5MG/ML - SOLUCAO ORAL',
    unificado: null,
  },
];
