import prescriptions from './components/Prescriptions.vue';
import departments from './components/Departments.vue';
import StatusTickets from './components/StatusTickets.vue';
import clients from './components/Clients';
import users from './components/Users';
import issueTypes from './components/IssueTypes';
import VueCronometro from 'vue-cronometro';
import Timeselector from 'vue-timeselector';
import VModal from 'vue-js-modal';
import UserModal from "./components/UserModal";
import ReportFilters from "./components/Reports/ReportFilters/ReportFilters";
import ReportLists from "./components/Reports/ReportLists/ReportLists";
import GenericList from "./components/GenericList";
import { Notifications } from "src/components";
import { Pharmacos } from "src/components";
import { Patients } from "src/components";
import { Doctors } from "src/components";
import { TimeTracker } from "src/components";
import { JiraIntegration } from "src/components";
import { Tabs, Tab } from 'vue-tabs-component';
import { ImageUpload } from "src/components";
import { JiraActions } from "src/components";
import { Answer } from "src/components";
import { Tags } from "src/components";
import { Pagination as LPagination } from "src/components/index";
import { Multiselect } from 'vue-multiselect';
import { MenuTicket } from "src/components";
// import { Navbar, FormCheckbox } from 'bootstrap-vue/es/components';
import { SidebarTicket } from "src/components";
import { Slas } from "src/components";
import { TelInput } from "src/components";
import { Profiles } from "src/components";
import { Priority } from "./components";
import { MakeSplit } from "src/components";
import { MakeMerge } from "src/components";
import { ClosedTicketsPerCompany } from "src/components";
import { Icon } from "src/components";
import { DropdownMenu } from "src/components";
import { Templates } from "src/components";
import { PaginationInTable } from "src/components";
import { TypesOfTemplate } from "src/components";
import { Channels } from "src/components";
import { ProfilesByTypeOfUser } from "src/components";
import { SatisfactionSurveys } from "src/components";
import { SearchType } from "src/components";
import { SidebarMenu } from "src/components";

const GlobalComponents = {
  install(Vue) {    
    Vue.component('sidebar-menu', SidebarMenu);
    Vue.component('search-type', SearchType);
    Vue.component('satisfaction-surveys', SatisfactionSurveys);
    Vue.component('profiles-by-type-of-user', ProfilesByTypeOfUser);
    Vue.component('channels', Channels);
    Vue.component('types-of-template', TypesOfTemplate);
    Vue.component('pagination-in-table', PaginationInTable);
    Vue.component('templates', Templates);
    Vue.component('dropdown-menu', DropdownMenu);
    Vue.component('icon', Icon);
    Vue.component('closed-tickets-per-company', ClosedTicketsPerCompany);
    Vue.component('make-split', MakeSplit);
    Vue.component('make-merge', MakeMerge);
    Vue.component('l-pagination', LPagination);
    Vue.component('tel-input', TelInput);
    Vue.component('answer', Answer);
    Vue.component('v-modal', VModal);
    Vue.component('time-selector', Timeselector);
    Vue.component('vue-cronometro', VueCronometro);
    Vue.component('tabs', Tabs);
    Vue.component('pharmacos', Pharmacos);
    Vue.component('patients', Patients);
    Vue.component('doctors', Doctors);
    Vue.component('tags', Tags);
    Vue.component('image-upload', ImageUpload);
    Vue.component('jira-actions', JiraActions);
    Vue.component('jira-integration', JiraIntegration);
    Vue.component('tab', Tab);
    Vue.component('time-tracker', TimeTracker);
    Vue.component('notifications', Notifications);
    Vue.component('prescriptions', prescriptions);
    Vue.component('departments', departments);
    Vue.component('StatusTickets', StatusTickets);
    Vue.component('clients', clients);
    Vue.component('issue-types', issueTypes);
    Vue.component('users', users);
    Vue.component('user-modal', UserModal);
    Vue.component('multiselect', Multiselect);
    Vue.component('MenuTicket', MenuTicket);
    Vue.component('report-filters', ReportFilters);
    Vue.component('report-lists', ReportLists);
    Vue.component('generic-list', GenericList);
    Vue.component('SidebarTicket', SidebarTicket);
    Vue.component('profiles', Profiles);
    Vue.component('prioritys', Priority);
    Vue.component('slas', Slas);
    Vue.use(MakeSplit);
  }
};

export default GlobalComponents;
